#include "Epidemic/GameFramework/Economy/economy.h"
#include "Epidemic/Foundation/error.h"
#include <algorithm>
#include <iterator>
#include <utility>
namespace epidemic::gameplay::economy
{
namespace{foundation::Error Error(std::string_view c,std::string_view m){return foundation::Error::Create(c,m);}}
EconomyService::EconomyService()=default;
foundation::Result<CurrencyId> EconomyService::RegisterCurrency(CurrencyDefinition d){if(frozen_)return foundation::Result<CurrencyId>::Failure(Error("gameplay.economy.frozen","economy definitions frozen"));if(!d.id.IsValid())d.id=CurrencyId::FromString(d.canonical_name);if(!d.id.IsValid()||d.smallest_unit<=0||currencies_.contains(d.id))return foundation::Result<CurrencyId>::Failure(Error("gameplay.economy.invalid_currency","invalid/duplicate currency"));d.revision=Revision{1};const auto id=d.id;currencies_.emplace(id,std::move(d));return foundation::Result<CurrencyId>::Success(id);}
foundation::Result<EconomicAccountId> EconomyService::CreateAccount(EconomicAccount a){if(!a.owner.IsValid()||!currencies_.contains(a.currency)||a.balance<0)return foundation::Result<EconomicAccountId>::Failure(Error("gameplay.economy.invalid_account","invalid account"));if(!a.id.IsValid())a.id=EconomicAccountId{account_ids_.Next()};if(accounts_.contains(a.id))return foundation::Result<EconomicAccountId>::Failure(Error("gameplay.economy.duplicate_account","duplicate account"));Bump();a.revision=revision_;const auto id=a.id;accounts_.emplace(id,a);++diagnostics_.accounts;Record({0,EconomyChangeKind::AccountCreated,a.owner,id,{},a.balance,{},revision_});return foundation::Result<EconomicAccountId>::Success(id);}
const EconomicAccount* EconomyService::FindAccount(EconomicAccountId id)const noexcept{auto it=accounts_.find(id);return it==accounts_.end()?nullptr:&it->second;}
Fixed EconomyService::GetBalance(EconomicAccountId id)const noexcept{const auto*a=FindAccount(id);return a?a->balance:0;}
Fixed EconomyService::GetAvailableBalance(EconomicAccountId id)const noexcept{Fixed r=0;for(const auto&[rid,v]:reservations_){(void)rid;if(v.account==id&&v.state==FundsReservationState::Active)r+=v.amount;}return std::max<Fixed>(0,GetBalance(id)-r);}
foundation::Result<void> EconomyService::Credit(EconomicAccountId id,Fixed amount,GameplayContext c){auto it=accounts_.find(id);if(it==accounts_.end()||amount<0||it->second.state!=AccountState::Active)return foundation::Result<void>::Failure(Error("gameplay.economy.credit_invalid","credit invalid"));Bump();it->second.balance+=amount;it->second.revision=revision_;Record({0,EconomyChangeKind::BalanceChanged,it->second.owner,id,{},amount,c,revision_});return foundation::Result<void>::Success();}
foundation::Result<void> EconomyService::Debit(EconomicAccountId id,Fixed amount,GameplayContext c){auto it=accounts_.find(id);if(it==accounts_.end()||amount<0||it->second.state!=AccountState::Active||GetAvailableBalance(id)<amount)return foundation::Result<void>::Failure(Error("gameplay.economy.insufficient_funds","debit exceeds available funds"));Bump();it->second.balance-=amount;it->second.revision=revision_;Record({0,EconomyChangeKind::BalanceChanged,it->second.owner,id,{},-amount,c,revision_});return foundation::Result<void>::Success();}
FundsReservation* EconomyService::MutableReservation(FundsReservationId id)noexcept{auto it=reservations_.find(id);return it==reservations_.end()?nullptr:&it->second;}
foundation::Result<FundsReservationId> EconomyService::ReserveFunds(EconomicAccountId account,Fixed amount,GameplayObjectRef beneficiary,TypeId reason,GameplayContext c){const auto*a=FindAccount(account);if(!a||amount<=0||GetAvailableBalance(account)<amount)return foundation::Result<FundsReservationId>::Failure(Error("gameplay.economy.insufficient_funds","funds unavailable"));FundsReservation r;r.id=FundsReservationId{reservation_ids_.Next()};r.account=account;r.amount=amount;r.beneficiary=beneficiary;r.reason=reason;Bump();r.revision=revision_;const auto id=r.id;reservations_.emplace(id,r);++diagnostics_.active_reservations;Record({0,EconomyChangeKind::FundsReserved,a->owner,account,{},amount,c,revision_});return foundation::Result<FundsReservationId>::Success(id);}
foundation::Result<void> EconomyService::ReleaseFunds(FundsReservationId id,GameplayContext c){auto*r=MutableReservation(id);if(!r||r->state!=FundsReservationState::Active)return foundation::Result<void>::Failure(Error("gameplay.economy.reservation_missing","active funds reservation missing"));Bump();r->state=FundsReservationState::Released;r->revision=revision_;if(diagnostics_.active_reservations>0)--diagnostics_.active_reservations;Record({0,EconomyChangeKind::FundsReleased,{},r->account,{},r->amount,c,revision_});return foundation::Result<void>::Success();}
foundation::Result<void> EconomyService::CommitFunds(FundsReservationId id,EconomicAccountId destination,GameplayContext c){auto*r=MutableReservation(id);auto from=r?accounts_.find(r->account):accounts_.end();auto to=accounts_.find(destination);if(!r||r->state!=FundsReservationState::Active||from==accounts_.end()||to==accounts_.end()||from->second.currency!=to->second.currency||from->second.balance<r->amount)return foundation::Result<void>::Failure(Error("gameplay.economy.commit_invalid","funds reservation cannot be committed"));Bump();from->second.balance-=r->amount;to->second.balance+=r->amount;from->second.revision=to->second.revision=revision_;r->state=FundsReservationState::Committed;r->revision=revision_;if(diagnostics_.active_reservations>0)--diagnostics_.active_reservations;Record({0,EconomyChangeKind::FundsCommitted,to->second.owner,destination,{},r->amount,c,revision_});return foundation::Result<void>::Success();}
foundation::Result<MarketId> EconomyService::CreateMarket(MarketState m){if(!m.id.IsValid())m.id=MarketId{market_ids_.Next()};if(markets_.contains(m.id))return foundation::Result<MarketId>::Failure(Error("gameplay.economy.duplicate_market","duplicate market"));Bump();m.revision=revision_;const auto id=m.id;markets_.emplace(id,m);++diagnostics_.markets;return foundation::Result<MarketId>::Success(id);}
foundation::Result<void> EconomyService::SetMarketIndicator(MarketIndicator i){if(!markets_.contains(i.market)||!i.commodity.IsValid()||i.supply<0||i.demand<0||i.price_index_micro<0)return foundation::Result<void>::Failure(Error("gameplay.economy.invalid_indicator","invalid market indicator"));Bump();i.revision=revision_;indicators_[{i.market,i.commodity}]=i;Record({0,EconomyChangeKind::MarketChanged,{}, {},{},i.price_index_micro,{},revision_});return foundation::Result<void>::Success();}
std::optional<MarketIndicator> EconomyService::GetMarketIndicator(MarketId m,EconomicCommodityId c)const{auto it=indicators_.find({m,c});return it==indicators_.end()?std::nullopt:std::optional<MarketIndicator>{it->second};}
std::optional<PriceQuote> EconomyService::GetPriceQuote(EconomicValueRef subject,CurrencyId currency,GameplayObjectRef buyer,GameplayObjectRef seller)const{if(!currencies_.contains(currency))return std::nullopt;for(const auto*p:price_providers_)if(p){auto q=p->Quote(subject,currency,buyer,seller);if(q)return q;}return std::nullopt;}
foundation::Result<OfferId> EconomyService::CreateOffer(EconomicOffer o){if(!o.seller.IsValid()||!currencies_.contains(o.currency)||o.quantity<=0||o.unit_price<0)return foundation::Result<OfferId>::Failure(Error("gameplay.economy.invalid_offer","invalid economic offer"));if(!o.id.IsValid())o.id=OfferId{offer_ids_.Next()};Bump();o.revision=revision_;const auto id=o.id;offers_[id]=o;++diagnostics_.offers;Record({0,EconomyChangeKind::OfferCreated,o.seller,{}, {},o.unit_price,{},revision_});return foundation::Result<OfferId>::Success(id);}
std::vector<EconomicOffer> EconomyService::FindOffers(GameplayObjectRef seller,OfferState state)const{std::vector<EconomicOffer>out;for(const auto&[id,o]:offers_){(void)id;if(o.state==state&&(!seller.IsValid()||o.seller==seller))out.push_back(o);}std::sort(out.begin(),out.end(),[](auto&a,auto&b){return a.id<b.id;});return out;}
std::vector<OfferId> EconomyService::ExpireOffers(GameplayTimePoint now,GameplayContext c){std::vector<OfferId>out;for(auto&[id,o]:offers_)if(o.state==OfferState::Active&&o.expires_at.ticks!=0&&o.expires_at<=now){Bump();o.state=OfferState::Expired;o.revision=revision_;out.push_back(id);Record({0,EconomyChangeKind::OfferChanged,o.seller,{}, {},0,c,revision_});}std::sort(out.begin(),out.end());return out;}
foundation::Result<void> EconomyService::ValidateTransfer(const MonetaryTransfer&t)const{const auto*a=FindAccount(t.from),*b=FindAccount(t.to);if(!a||!b||t.amount<=0||a->currency!=t.currency||b->currency!=t.currency||GetAvailableBalance(t.from)<t.amount)return foundation::Result<void>::Failure(Error("gameplay.economy.transfer_invalid","invalid monetary transfer"));return foundation::Result<void>::Success();}
foundation::Result<TradeTransactionId> EconomyService::PrepareTrade(TradePlan p){for(const auto&t:p.monetary_transfers){auto v=ValidateTransfer(t);if(!v)return foundation::Result<TradeTransactionId>::Failure(v.GetError());}if(!p.id.IsValid())p.id=TradeTransactionId{transaction_ids_.Next()};TradeTransaction tx;tx.id=p.id;tx.plan=std::move(p);tx.state=TradeTransactionState::Prepared;Bump();tx.revision=revision_;const auto id=tx.id;transactions_.emplace(id,std::move(tx));++diagnostics_.transactions;Record({0,EconomyChangeKind::TradeChanged,{}, {},id,0,{},revision_});return foundation::Result<TradeTransactionId>::Success(id);}
foundation::Result<void> EconomyService::ReserveTrade(TradeTransactionId id){auto it=transactions_.find(id);if(it==transactions_.end()||it->second.state!=TradeTransactionState::Prepared)return foundation::Result<void>::Failure(Error("gameplay.economy.trade_state","trade not prepared"));std::vector<FundsReservationId> made;for(const auto&t:it->second.plan.monetary_transfers){auto r=ReserveFunds(t.from,t.amount,{},TypeId::FromString("economy.trade"),it->second.plan.context);if(!r){for(auto rid:made)(void)ReleaseFunds(rid,it->second.plan.context);return foundation::Result<void>::Failure(r.GetError());}made.push_back(r.Value());}Bump();it->second.reservations=std::move(made);it->second.state=TradeTransactionState::Reserved;it->second.revision=revision_;Record({0,EconomyChangeKind::TradeChanged,{}, {},id,0,it->second.plan.context,revision_});return foundation::Result<void>::Success();}
foundation::Result<void> EconomyService::CommitTrade(TradeTransactionId id)
{
    auto it=transactions_.find(id);
    if(it==transactions_.end())return foundation::Result<void>::Failure(Error("gameplay.economy.trade_missing","trade missing"));
    if(it->second.state==TradeTransactionState::Committed)return foundation::Result<void>::Success();
    if(it->second.state!=TradeTransactionState::Reserved||it->second.reservations.size()!=it->second.plan.monetary_transfers.size())return foundation::Result<void>::Failure(Error("gameplay.economy.trade_state","trade not reserved"));
    std::unordered_map<EconomicAccountId,Fixed,IdHash> outgoing;
    for(std::size_t i=0;i<it->second.reservations.size();++i)
    {
        const auto rid=it->second.reservations[i];
        const auto* reservation=MutableReservation(rid);
        const auto& transfer=it->second.plan.monetary_transfers[i];
        const auto from=accounts_.find(transfer.from),to=accounts_.find(transfer.to);
        if(!reservation||reservation->state!=FundsReservationState::Active||reservation->account!=transfer.from||reservation->amount!=transfer.amount||from==accounts_.end()||to==accounts_.end()||from->second.currency!=transfer.currency||to->second.currency!=transfer.currency)return foundation::Result<void>::Failure(Error("gameplay.economy.trade_invalidated","reserved trade was invalidated"));
        outgoing[transfer.from]+=transfer.amount;
    }
    for(const auto&[account,amount]:outgoing){const auto a=accounts_.find(account);if(a==accounts_.end()||a->second.balance<amount)return foundation::Result<void>::Failure(Error("gameplay.economy.trade_invalidated","reserved trade funds unavailable"));}
    Bump();
    for(std::size_t i=0;i<it->second.reservations.size();++i)
    {
        auto* reservation=MutableReservation(it->second.reservations[i]);
        const auto& transfer=it->second.plan.monetary_transfers[i];
        auto& from=accounts_.at(transfer.from);auto& to=accounts_.at(transfer.to);
        from.balance-=transfer.amount;to.balance+=transfer.amount;from.revision=to.revision=revision_;reservation->state=FundsReservationState::Committed;reservation->revision=revision_;if(diagnostics_.active_reservations>0)--diagnostics_.active_reservations;Record({0,EconomyChangeKind::FundsCommitted,to.owner,transfer.to,id,transfer.amount,it->second.plan.context,revision_});
    }
    it->second.state=TradeTransactionState::Committed;it->second.revision=revision_;Record({0,EconomyChangeKind::TradeChanged,{}, {},id,0,it->second.plan.context,revision_});return foundation::Result<void>::Success();
}
foundation::Result<void> EconomyService::CancelTrade(TradeTransactionId id){auto it=transactions_.find(id);if(it==transactions_.end())return foundation::Result<void>::Failure(Error("gameplay.economy.trade_missing","trade missing"));if(it->second.state==TradeTransactionState::Committed)return foundation::Result<void>::Failure(Error("gameplay.economy.trade_committed","committed trade cannot be cancelled"));for(auto rid:it->second.reservations){auto*r=MutableReservation(rid);if(r&&r->state==FundsReservationState::Active)(void)ReleaseFunds(rid,it->second.plan.context);}Bump();it->second.state=TradeTransactionState::Cancelled;it->second.revision=revision_;Record({0,EconomyChangeKind::TradeChanged,{}, {},id,0,it->second.plan.context,revision_});return foundation::Result<void>::Success();}
const TradeTransaction* EconomyService::FindTransaction(TradeTransactionId id)const noexcept{auto it=transactions_.find(id);return it==transactions_.end()?nullptr:&it->second;}
foundation::Result<DebtId> EconomyService::CreateDebt(DebtRecord d){if(!d.debtor.IsValid()||!d.creditor.IsValid()||!currencies_.contains(d.currency)||d.principal<=0)return foundation::Result<DebtId>::Failure(Error("gameplay.economy.invalid_debt","invalid debt"));if(!d.id.IsValid())d.id=DebtId{debt_ids_.Next()};Bump();d.revision=revision_;const auto id=d.id;debts_[id]=d;++diagnostics_.debts;Record({0,EconomyChangeKind::DebtChanged,d.debtor,{}, {},d.principal,{},revision_});return foundation::Result<DebtId>::Success(id);}
foundation::Result<void> EconomyService::ResolveDebt(DebtId id,DebtState s,GameplayContext c){auto it=debts_.find(id);if(it==debts_.end())return foundation::Result<void>::Failure(Error("gameplay.economy.debt_missing","debt missing"));Bump();it->second.state=s;it->second.revision=revision_;Record({0,EconomyChangeKind::DebtChanged,it->second.debtor,{}, {},it->second.principal,c,revision_});return foundation::Result<void>::Success();}
std::vector<DebtRecord> EconomyService::FindDebts(GameplayObjectRef s)const{std::vector<DebtRecord>out;for(const auto&[id,d]:debts_){(void)id;if(d.debtor==s||d.creditor==s)out.push_back(d);}std::sort(out.begin(),out.end(),[](auto&a,auto&b){return a.id<b.id;});return out;}
foundation::Result<EconomicContractId> EconomyService::CreateContract(EconomicContract c){if(c.parties.size()<2||!c.type.IsValid()||!currencies_.contains(c.currency)||c.amount<0)return foundation::Result<EconomicContractId>::Failure(Error("gameplay.economy.invalid_contract","invalid economic contract"));if(!c.id.IsValid())c.id=EconomicContractId{contract_ids_.Next()};Bump();c.revision=revision_;const auto id=c.id;contracts_[id]=std::move(c);Record({0,EconomyChangeKind::ContractChanged,{}, {},{},0,{},revision_});return foundation::Result<EconomicContractId>::Success(id);}
foundation::Result<void> EconomyService::SetContractState(EconomicContractId id,ContractState s,GameplayContext c){auto it=contracts_.find(id);if(it==contracts_.end())return foundation::Result<void>::Failure(Error("gameplay.economy.contract_missing","contract missing"));Bump();it->second.state=s;it->second.revision=revision_;Record({0,EconomyChangeKind::ContractChanged,{}, {},{},it->second.amount,c,revision_});return foundation::Result<void>::Success();}
std::vector<EconomyChange> EconomyService::ChangesSince(std::uint64_t seq)const{std::vector<EconomyChange>out;std::copy_if(changes_.begin(),changes_.end(),std::back_inserter(out),[seq](auto&c){return c.sequence>seq;});return out;}
EconomySnapshot EconomyService::CaptureSnapshot()const{EconomySnapshot s;for(const auto&[id,v]:accounts_){(void)id;s.accounts.push_back(v);}for(const auto&[id,v]:reservations_){(void)id;s.reservations.push_back(v);}for(const auto&[id,v]:markets_){(void)id;s.markets.push_back(v);}for(const auto&[id,v]:indicators_){(void)id;s.indicators.push_back(v);}for(const auto&[id,v]:offers_){(void)id;s.offers.push_back(v);}for(const auto&[id,v]:transactions_){(void)id;s.transactions.push_back(v);}for(const auto&[id,v]:debts_){(void)id;s.debts.push_back(v);}for(const auto&[id,v]:contracts_){(void)id;s.contracts.push_back(v);}auto sorter=[](auto&a,auto&b){return a.id<b.id;};std::sort(s.accounts.begin(),s.accounts.end(),sorter);std::sort(s.reservations.begin(),s.reservations.end(),sorter);std::sort(s.markets.begin(),s.markets.end(),sorter);std::sort(s.offers.begin(),s.offers.end(),sorter);std::sort(s.transactions.begin(),s.transactions.end(),sorter);std::sort(s.debts.begin(),s.debts.end(),sorter);std::sort(s.contracts.begin(),s.contracts.end(),sorter);std::sort(s.indicators.begin(),s.indicators.end(),[](auto&a,auto&b){return a.market==b.market?a.commodity<b.commodity:a.market<b.market;});s.account_ids=account_ids_.GetSnapshot();s.reservation_ids=reservation_ids_.GetSnapshot();s.market_ids=market_ids_.GetSnapshot();s.offer_ids=offer_ids_.GetSnapshot();s.transaction_ids=transaction_ids_.GetSnapshot();s.debt_ids=debt_ids_.GetSnapshot();s.contract_ids=contract_ids_.GetSnapshot();s.revision=revision_;return s;}
foundation::Result<void> EconomyService::RestoreSnapshot(EconomySnapshot s){std::unordered_map<EconomicAccountId,EconomicAccount,IdHash>a;for(auto&v:s.accounts){if(!v.id.IsValid()||!currencies_.contains(v.currency)||a.contains(v.id))return foundation::Result<void>::Failure(Error("gameplay.economy.restore_invalid","invalid account snapshot"));a.emplace(v.id,std::move(v));}std::unordered_map<FundsReservationId,FundsReservation,IdHash>r;for(auto&v:s.reservations){if(!v.id.IsValid()||!a.contains(v.account)||r.contains(v.id))return foundation::Result<void>::Failure(Error("gameplay.economy.restore_invalid","invalid reservation snapshot"));r.emplace(v.id,std::move(v));}accounts_=std::move(a);reservations_=std::move(r);markets_.clear();for(auto&v:s.markets)markets_.emplace(v.id,std::move(v));indicators_.clear();for(auto&v:s.indicators)indicators_[{v.market,v.commodity}]=std::move(v);offers_.clear();for(auto&v:s.offers)offers_.emplace(v.id,std::move(v));transactions_.clear();for(auto&v:s.transactions)transactions_.emplace(v.id,std::move(v));debts_.clear();for(auto&v:s.debts)debts_.emplace(v.id,std::move(v));contracts_.clear();for(auto&v:s.contracts)contracts_.emplace(v.id,std::move(v));account_ids_.Restore(s.account_ids);reservation_ids_.Restore(s.reservation_ids);market_ids_.Restore(s.market_ids);offer_ids_.Restore(s.offer_ids);transaction_ids_.Restore(s.transaction_ids);debt_ids_.Restore(s.debt_ids);contract_ids_.Restore(s.contract_ids);revision_=s.revision;changes_.clear();next_change_sequence_=1;diagnostics_={};diagnostics_.accounts=accounts_.size();diagnostics_.markets=markets_.size();diagnostics_.offers=offers_.size();diagnostics_.transactions=transactions_.size();diagnostics_.debts=debts_.size();for(const auto&[id,v]:reservations_){(void)id;if(v.state==FundsReservationState::Active)++diagnostics_.active_reservations;}return foundation::Result<void>::Success();}
EconomyDiagnostics EconomyService::GetDiagnostics()const noexcept{return diagnostics_;}
void EconomyService::Record(EconomyChange c){c.sequence=next_change_sequence_++;changes_.push_back(std::move(c));}
}
