#include "Epidemic/GameFramework/SaveGame/save_game.h"
#include "Epidemic/Foundation/error.h"
#include "Epidemic/Foundation/error.h"
#include <cstdlib>
#include <cstring>
#include <iostream>
using namespace epidemic::gameplay;using namespace epidemic::gameplay::savegame;
namespace{void Check(bool v,const char*m){if(!v){std::cerr<<m<<'\n';std::exit(1);}}struct Stage final:IRestoreStage{int value=0;};class Part final:public ISaveParticipant{public:SaveParticipantId id{};SaveSchemaVersion version=1;std::vector<SaveParticipantId>deps;int value=0;bool fail_stage=false;SaveParticipantId Id()const noexcept override{return id;}SaveSchemaVersion SchemaVersion()const noexcept override{return version;}std::vector<SaveParticipantId> Dependencies()const override{return deps;}epidemic::foundation::Result<SaveSection> CaptureSnapshot(const SaveContext&)const override{SaveSection s;s.participant=id;s.schema_version=version;s.payload.resize(sizeof(value));std::memcpy(s.payload.data(),&value,sizeof(value));return epidemic::foundation::Result<SaveSection>::Success(std::move(s));}epidemic::foundation::Result<void> ValidateSnapshot(const SaveSection&s,const RestoreContext&)const override{return s.payload.size()==sizeof(int)?epidemic::foundation::Result<void>::Success():epidemic::foundation::Result<void>::Failure(epidemic::foundation::Error::Create("invalid","invalid"));}epidemic::foundation::Result<std::unique_ptr<IRestoreStage>> StageRestore(const SaveSection&s,const RestoreContext&)override{if(fail_stage)return epidemic::foundation::Result<std::unique_ptr<IRestoreStage>>::Failure(epidemic::foundation::Error::Create("stage","failed"));auto st=std::make_unique<Stage>();std::memcpy(&st->value,s.payload.data(),sizeof(int));return epidemic::foundation::Result<std::unique_ptr<IRestoreStage>>::Success(std::move(st));}epidemic::foundation::Result<void> CommitRestore(IRestoreStage&s)override{value=static_cast<Stage&>(s).value;return epidemic::foundation::Result<void>::Success();}};}
int main(){Part a;a.id=SaveParticipantId::FromString("a");a.value=11;Part b;b.id=SaveParticipantId::FromString("b");b.value=22;b.deps={a.id};SaveGameOrchestrator o;Check(static_cast<bool>(o.RegisterParticipant(a)),"register a");Check(static_cast<bool>(o.RegisterParticipant(b)),"register b");auto order=o.ResolveOrder();Check(static_cast<bool>(order)&&order.Value().size()==2&&order.Value()[0]==a.id,"dependency order");SaveContext sc;sc.content_version=4;sc.content_hash=99;auto image=o.Capture(sc);Check(static_cast<bool>(image),"capture");a.value=100;b.value=200;b.fail_stage=true;RestoreContext rc;rc.current_content_version=4;rc.current_content_hash=99;Check(!o.Restore(image.Value(),rc),"staging failure");Check(a.value==100&&b.value==200,"staging failure leaves live state untouched");b.fail_stage=false;Check(static_cast<bool>(o.Restore(image.Value(),rc)),"restore");Check(a.value==11&&b.value==22,"values restored");Part c;c.id=SaveParticipantId::FromString("c");c.deps={SaveParticipantId::FromString("d")};Part d;d.id=SaveParticipantId::FromString("d");d.deps={c.id};SaveGameOrchestrator cycle;Check(static_cast<bool>(cycle.RegisterParticipant(c))&&static_cast<bool>(cycle.RegisterParticipant(d)),"cycle participants");Check(!cycle.ResolveOrder(),"dependency cycle rejected");return 0;}
