set(EPIDEMIC_GAMEFRAMEWORK_CORE_MODULES
    Foundation Queries Facts Time Entities Materials Conditions Effects World Environment Interaction SupportRandom
    Progression Combat Abilities Loot Traversal NavigationSemantics Construction Perception Knowledge AI Ownership
    Society Crime Population Encounters RolesJobs NeedsLife Processes ResourcesProduction Simulation Narrative
    ItemsInventory Equipment Dialogue Economy SaveGame)

set(EPIDEMIC_GAMEFRAMEWORK_INTEGRATION_MODULES
    Integration StateIntegration WorldIntegration InteractionEffectsIntegration InteractionTimeIntegration RuntimeBridge
    GameplayIntegration TraversalNavigationConstructionIntegration PerceptionKnowledgeAIIntegration SocialLegalIntegration
    PopulationSimulationIntegration ProcessResourceSimulationIntegration NarrativeIntegration ExtendedGameplayIntegration)

set(EPIDEMIC_GAMEFRAMEWORK_ALLOWED_CORE_DEPS Foundation SupportRandom)

set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Foundation EpidemicGameFrameworkFoundation)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Queries EpidemicGameplayQueries)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Facts EpidemicGameplayFacts)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Time EpidemicGameplayTime)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Entities EpidemicGameFrameworkEntities)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Materials EpidemicGameFrameworkMaterials)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Conditions EpidemicGameFrameworkConditions)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Effects EpidemicGameFrameworkEffects)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_World EpidemicGameFrameworkWorld)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Environment EpidemicGameFrameworkEnvironment)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Interaction EpidemicGameFrameworkInteraction)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_SupportRandom EpidemicGameFrameworkSupportRandom)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Progression EpidemicGameFrameworkProgression)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Combat EpidemicGameFrameworkCombat)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Abilities EpidemicGameFrameworkAbilities)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Loot EpidemicGameFrameworkLoot)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Traversal EpidemicGameFrameworkTraversal)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_NavigationSemantics EpidemicGameFrameworkNavigationSemantics)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Construction EpidemicGameFrameworkConstruction)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Perception EpidemicGameFrameworkPerception)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Knowledge EpidemicGameFrameworkKnowledge)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_AI EpidemicGameFrameworkAI)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Ownership EpidemicGameFrameworkOwnership)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Society EpidemicGameFrameworkSociety)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Crime EpidemicGameFrameworkCrime)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Population EpidemicGameFrameworkPopulation)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Encounters EpidemicGameFrameworkEncounters)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_RolesJobs EpidemicGameFrameworkRolesJobs)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_NeedsLife EpidemicGameFrameworkNeedsLife)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Processes EpidemicGameFrameworkProcesses)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_ResourcesProduction EpidemicGameFrameworkResourcesProduction)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Simulation EpidemicGameFrameworkSimulation)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Narrative EpidemicGameFrameworkNarrative)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_ItemsInventory EpidemicGameFrameworkItemsInventory)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Equipment EpidemicGameFrameworkEquipment)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Dialogue EpidemicGameFrameworkDialogue)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Economy EpidemicGameFrameworkEconomy)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_SaveGame EpidemicGameFrameworkSaveGame)

function(epidemic_validate_framework_architecture)
    set(_all_modules ${EPIDEMIC_GAMEFRAMEWORK_CORE_MODULES} ${EPIDEMIC_GAMEFRAMEWORK_INTEGRATION_MODULES})
    set(_all_targets)
    foreach(_module IN LISTS _all_modules)
        if(DEFINED EPIDEMIC_GAMEFRAMEWORK_TARGET_${_module})
            list(APPEND _all_targets "${EPIDEMIC_GAMEFRAMEWORK_TARGET_${_module}}")
        endif()
    endforeach()

    foreach(_module IN LISTS EPIDEMIC_GAMEFRAMEWORK_CORE_MODULES)
        set(_target "${EPIDEMIC_GAMEFRAMEWORK_TARGET_${_module}}")
        if(TARGET "${_target}")
            get_target_property(_links "${_target}" LINK_LIBRARIES)
            get_target_property(_interface_links "${_target}" INTERFACE_LINK_LIBRARIES)
            foreach(_dep IN LISTS _links _interface_links)
                list(FIND _all_targets "${_dep}" _dep_index)
                if(_dep_index GREATER -1)
                    set(_allowed FALSE)
                    foreach(_allowed_module IN LISTS EPIDEMIC_GAMEFRAMEWORK_ALLOWED_CORE_DEPS)
                        if(_dep STREQUAL "${EPIDEMIC_GAMEFRAMEWORK_TARGET_${_allowed_module}}")
                            set(_allowed TRUE)
                        endif()
                    endforeach()
                    if(_dep STREQUAL "${_target}")
                        set(_allowed TRUE)
                    endif()
                    if(NOT _allowed)
                        message(FATAL_ERROR "${_target} links gameplay module '${_dep}' without central allowlist permission.")
                    endif()
                endif()
            endforeach()
        endif()

        file(GLOB_RECURSE _module_sources CONFIGURE_DEPENDS
            "${CMAKE_CURRENT_LIST_DIR}/../${_module}/include/*.h"
            "${CMAKE_CURRENT_LIST_DIR}/../${_module}/src/*.cpp")
        foreach(_file IN LISTS _module_sources)
            file(READ "${_file}" _content)
            foreach(_other IN LISTS _all_modules)
                if(NOT _other STREQUAL _module)
                    list(FIND EPIDEMIC_GAMEFRAMEWORK_ALLOWED_CORE_DEPS "${_other}" _allow_index)
                    if(_allow_index EQUAL -1 AND _content MATCHES "Epidemic/GameFramework/${_other}/")
                        message(FATAL_ERROR "${_module} includes GameFramework/${_other} from ${_file} without central allowlist permission.")
                    endif()
                endif()
            endforeach()
        endforeach()
    endforeach()
endfunction()
