add_subdirectory(RuntimeFoundation)
add_subdirectory(Assets)
add_subdirectory(Resources)
add_subdirectory(Serialization)
add_subdirectory(Persistence)
add_subdirectory(Time)
add_subdirectory(Environment)
add_subdirectory(Scene)
add_subdirectory(World)
add_subdirectory(Streaming)
add_subdirectory(Renderer)
add_subdirectory(Physics)
add_subdirectory(Navigation)
add_subdirectory(Animation)
add_subdirectory(Audio)
add_subdirectory(Simulation)
add_subdirectory(Support)
if(BUILD_TESTING)
    add_subdirectory(Tests)
endif()

