#include "Epidemic/GameFramework/Dialogue/dialogue.h"
#include "Epidemic/Foundation/error.h"
#include <algorithm>
#include <iterator>
#include <utility>
namespace epidemic::gameplay::dialogue
{
namespace{foundation::Error Error(std::string_view c,std::string_view m){return foundation::Error::Create(c,m);}}
foundation::Result<void> DialogueService::RegisterCondition(DialogueConditionDefinition d){if(frozen_||!d.id.IsValid()||!d.type.IsValid()||conditions_.contains(d.id))return foundation::Result<void>::Failure(Error("gameplay.dialogue.invalid_condition","invalid/duplicate dialogue condition"));conditions_.emplace(d.id,std::move(d));return foundation::Result<void>::Success();}
foundation::Result<void> DialogueService::RegisterConsequence(DialogueConsequenceDefinition d){if(frozen_||!d.id.IsValid()||!d.type.IsValid()||consequence_defs_.contains(d.id))return foundation::Result<void>::Failure(Error("gameplay.dialogue.invalid_consequence","invalid/duplicate dialogue consequence"));consequence_defs_.emplace(d.id,std::move(d));return foundation::Result<void>::Success();}
foundation::Result<ConversationDefinitionId> DialogueService::RegisterConversation(ConversationDefinition d){if(frozen_)return foundation::Result<ConversationDefinitionId>::Failure(Error("gameplay.dialogue.frozen","dialogue definitions frozen"));if(!d.id.IsValid())d.id=ConversationDefinitionId::FromString(d.canonical_name);if(!d.id.IsValid()||!d.entry_node.IsValid()||definitions_.contains(d.id))return foundation::Result<ConversationDefinitionId>::Failure(Error("gameplay.dialogue.invalid_definition","invalid/duplicate conversation definition"));std::unordered_set<DialogueNodeId,IdHash> nodes;for(const auto&n:d.nodes){if(!n.id.IsValid()||!nodes.insert(n.id).second)return foundation::Result<ConversationDefinitionId>::Failure(Error("gameplay.dialogue.invalid_graph","duplicate/invalid dialogue node"));for(const auto&o:n.options)if(!o.id.IsValid())return foundation::Result<ConversationDefinitionId>::Failure(Error("gameplay.dialogue.invalid_graph","invalid dialogue option"));}if(!nodes.contains(d.entry_node))return foundation::Result<ConversationDefinitionId>::Failure(Error("gameplay.dialogue.invalid_graph","entry node missing"));d.revision=Revision{1};const auto id=d.id;definitions_.emplace(id,std::move(d));diagnostics_.definitions=definitions_.size();return foundation::Result<ConversationDefinitionId>::Success(id);}
foundation::Result<void> DialogueService::RegisterConditionResolver(DialogueConditionTypeId t,const IDialogueConditionResolver&r){if(frozen_||!t.IsValid()||condition_resolvers_.contains(t))return foundation::Result<void>::Failure(Error("gameplay.dialogue.invalid_resolver","invalid/duplicate condition resolver"));condition_resolvers_[t]=&r;return foundation::Result<void>::Success();}
foundation::Result<void> DialogueService::RegisterConsequenceHandler(DialogueConsequenceTypeId t,const IDialogueConsequenceHandler&h){if(frozen_||!t.IsValid()||consequence_handlers_.contains(t))return foundation::Result<void>::Failure(Error("gameplay.dialogue.invalid_handler","invalid/duplicate consequence handler"));consequence_handlers_[t]=&h;return foundation::Result<void>::Success();}
foundation::Result<void> DialogueService::FreezeDefinitions(){for(const auto&[id,d]:definitions_){(void)id;for(const auto&n:d.nodes){for(auto c:n.conditions)if(!conditions_.contains(c))return foundation::Result<void>::Failure(Error("gameplay.dialogue.unknown_condition","dialogue node references unknown condition"));for(auto c:n.consequences)if(!consequence_defs_.contains(c))return foundation::Result<void>::Failure(Error("gameplay.dialogue.unknown_consequence","dialogue node references unknown consequence"));for(const auto&o:n.options){for(auto c:o.conditions)if(!conditions_.contains(c))return foundation::Result<void>::Failure(Error("gameplay.dialogue.unknown_condition","dialogue option references unknown condition"));for(auto c:o.consequences)if(!consequence_defs_.contains(c))return foundation::Result<void>::Failure(Error("gameplay.dialogue.unknown_consequence","dialogue option references unknown consequence"));if(o.next_node.IsValid()&&!FindNode(d,o.next_node))return foundation::Result<void>::Failure(Error("gameplay.dialogue.unknown_node","dialogue option references unknown node"));}if(n.automatic_next.IsValid()&&!FindNode(d,n.automatic_next))return foundation::Result<void>::Failure(Error("gameplay.dialogue.unknown_node","dialogue automatic transition references unknown node"));}}frozen_=true;return foundation::Result<void>::Success();}
const DialogueNodeDefinition* DialogueService::FindNode(const ConversationDefinition&d,DialogueNodeId id)const noexcept{auto it=std::find_if(d.nodes.begin(),d.nodes.end(),[id](const auto&n){return n.id==id;});return it==d.nodes.end()?nullptr:&*it;}
const ConversationDefinition* DialogueService::GetDefinition(ConversationDefinitionId id)const noexcept{auto it=definitions_.find(id);return it==definitions_.end()?nullptr:&it->second;}
const ConversationSession* DialogueService::GetSession(ConversationSessionId id)const noexcept{auto it=sessions_.find(id);return it==sessions_.end()?nullptr:&it->second;}
bool DialogueService::ConditionsPass(const std::vector<TypeId>&ids,const DialogueConditionContext&ctx)const{for(auto id:ids){auto d=conditions_.find(id);if(d==conditions_.end())return false;auto r=condition_resolvers_.find(d->second.type);if(r==condition_resolvers_.end())return false;if(r->second->Evaluate(d->second,ctx).state!=DialogueConditionState::Satisfied)return false;}return true;}
void DialogueService::PlanConsequences(ConversationSessionId session,const std::vector<TypeId>&ids,GameplayContext context){std::vector<const DialogueConsequenceDefinition*> ordered;for(auto id:ids){auto it=consequence_defs_.find(id);if(it!=consequence_defs_.end())ordered.push_back(&it->second);}std::sort(ordered.begin(),ordered.end(),[](auto*a,auto*b){if(a->priority!=b->priority)return a->priority>b->priority;return a->id<b->id;});for(auto*d:ordered){DialogueConsequenceExecution e;e.id=DialogueConsequenceExecutionId{consequence_ids_.Next()};e.session=session;e.consequence=d->id;e.context=context;Bump();e.revision=revision_;consequences_.emplace(e.id,e);++diagnostics_.consequences;Record({0,DialogueChangeKind::ConsequencePlanned,session,{}, {},context,revision_});}}
foundation::Result<void> DialogueService::EnterNode(ConversationSession&s,DialogueNodeId node,GameplayContext context){const auto*d=GetDefinition(s.definition);const auto*n=d?FindNode(*d,node):nullptr;if(!n)return foundation::Result<void>::Failure(Error("gameplay.dialogue.node_missing","dialogue node missing"));DialogueConditionContext c{s.id,s.current_speaker,s.participants.size()>1?s.participants[1]:GameplayObjectRef{},s.context};if(!ConditionsPass(n->conditions,c))return foundation::Result<void>::Failure(Error("gameplay.dialogue.node_unavailable","dialogue node conditions failed"));const bool was_active=s.state!=ConversationState::Completed&&s.state!=ConversationState::Interrupted&&s.state!=ConversationState::Failed;Bump();s.current_node=node;s.state=n->options.empty()?(n->automatic_next.IsValid()?ConversationState::Active:ConversationState::Completed):ConversationState::WaitingForChoice;s.revision=revision_;PlanConsequences(s.id,n->consequences,context);Record({0,DialogueChangeKind::NodeEntered,s.id,node,{},context,revision_});if(s.state==ConversationState::Completed){if(was_active&&diagnostics_.active_sessions>0)--diagnostics_.active_sessions;Record({0,DialogueChangeKind::ConversationCompleted,s.id,node,{},context,revision_});}return foundation::Result<void>::Success();}
foundation::Result<ConversationSessionId> DialogueService::StartConversation(ConversationDefinitionId id,std::vector<GameplayObjectRef> participants,ConversationContext context){const auto*d=GetDefinition(id);if(!d||participants.size()<2)return foundation::Result<ConversationSessionId>::Failure(Error("gameplay.dialogue.cannot_start","conversation definition missing or participants invalid"));for(auto p:participants)if(!p.IsValid())return foundation::Result<ConversationSessionId>::Failure(Error("gameplay.dialogue.invalid_participant","invalid conversation participant"));ConversationSession s;s.id=ConversationSessionId{session_ids_.Next()};s.definition=id;s.participants=std::move(participants);s.current_speaker=s.participants.front();s.context=std::move(context);s.started_at=s.context.gameplay.time;s.state=ConversationState::Active;Bump();s.revision=revision_;const auto sid=s.id;sessions_.emplace(sid,std::move(s));++diagnostics_.active_sessions;Record({0,DialogueChangeKind::ConversationStarted,sid,d->entry_node,{},sessions_.at(sid).context.gameplay,revision_});auto r=EnterNode(sessions_.at(sid),d->entry_node,sessions_.at(sid).context.gameplay);if(!r){sessions_.erase(sid);if(diagnostics_.active_sessions>0)--diagnostics_.active_sessions;return foundation::Result<ConversationSessionId>::Failure(r.GetError());}return foundation::Result<ConversationSessionId>::Success(sid);}
std::vector<DialogueOptionDefinition> DialogueService::GetAvailableOptions(ConversationSessionId id,GameplayObjectRef actor)const{std::vector<DialogueOptionDefinition>out;const auto*s=GetSession(id);const auto*d=s?GetDefinition(s->definition):nullptr;const auto*n=d?FindNode(*d,s->current_node):nullptr;if(!s||!n||s->state!=ConversationState::WaitingForChoice)return out;DialogueConditionContext ctx{id,actor,{},s->context};for(const auto&o:n->options)if(!s->resolved_persistent_options.contains(o.id.value)&&ConditionsPass(o.conditions,ctx))out.push_back(o);std::sort(out.begin(),out.end(),[](auto&a,auto&b){return a.id<b.id;});return out;}
foundation::Result<void> DialogueService::SelectOption(ConversationSessionId id,DialogueOptionId option,GameplayObjectRef actor,GameplayContext context){auto it=sessions_.find(id);if(it==sessions_.end()||it->second.state!=ConversationState::WaitingForChoice)return foundation::Result<void>::Failure(Error("gameplay.dialogue.session_not_waiting","conversation is not waiting for a choice"));const auto options=GetAvailableOptions(id,actor);auto oit=std::find_if(options.begin(),options.end(),[option](const auto&o){return o.id==option;});if(oit==options.end())return foundation::Result<void>::Failure(Error("gameplay.dialogue.option_unavailable","dialogue option unavailable"));Bump();it->second.resolved_persistent_options.insert(option.value);it->second.revision=revision_;++diagnostics_.options_selected;Record({0,DialogueChangeKind::OptionSelected,id,it->second.current_node,option,context,revision_});PlanConsequences(id,oit->consequences,context);if(oit->next_node.IsValid())return EnterNode(it->second,oit->next_node,context);it->second.state=ConversationState::Completed;if(diagnostics_.active_sessions>0)--diagnostics_.active_sessions;Record({0,DialogueChangeKind::ConversationCompleted,id,it->second.current_node,option,context,revision_});return foundation::Result<void>::Success();}
foundation::Result<void> DialogueService::Advance(ConversationSessionId id,GameplayContext context){auto it=sessions_.find(id);if(it==sessions_.end())return foundation::Result<void>::Failure(Error("gameplay.dialogue.session_missing","conversation session missing"));const auto*d=GetDefinition(it->second.definition);const auto*n=d?FindNode(*d,it->second.current_node):nullptr;if(!n||!n->automatic_next.IsValid())return foundation::Result<void>::Failure(Error("gameplay.dialogue.no_automatic_transition","dialogue node has no automatic transition"));return EnterNode(it->second,n->automatic_next,context);}
foundation::Result<void> DialogueService::Interrupt(ConversationSessionId id,TypeId reason,GameplayContext context){auto it=sessions_.find(id);if(it==sessions_.end())return foundation::Result<void>::Failure(Error("gameplay.dialogue.session_missing","conversation session missing"));if(it->second.state==ConversationState::Completed||it->second.state==ConversationState::Interrupted)return foundation::Result<void>::Success();Bump();it->second.state=ConversationState::Interrupted;it->second.revision=revision_;if(diagnostics_.active_sessions>0)--diagnostics_.active_sessions;++diagnostics_.interruptions;(void)reason;Record({0,DialogueChangeKind::ConversationInterrupted,id,it->second.current_node,{},context,revision_});return foundation::Result<void>::Success();}
std::vector<DialogueConsequenceExecutionId> DialogueService::ExecutePendingConsequences(std::size_t budget){std::vector<DialogueConsequenceExecutionId> ids;for(const auto&[id,e]:consequences_)if(e.state==DialogueConsequenceState::Pending)ids.push_back(id);std::sort(ids.begin(),ids.end());if(ids.size()>budget)ids.resize(budget);std::vector<DialogueConsequenceExecutionId> applied;for(auto id:ids){auto& e=consequences_.at(id);auto d=consequence_defs_.find(e.consequence);auto s=sessions_.find(e.session);if(d==consequence_defs_.end()||s==sessions_.end()){e.state=DialogueConsequenceState::Failed;continue;}auto h=consequence_handlers_.find(d->second.type);if(h==consequence_handlers_.end()){e.state=DialogueConsequenceState::Deferred;continue;}const auto state=h->second->Execute(d->second,e,s->second);Bump();e.state=state;e.revision=revision_;if(state==DialogueConsequenceState::Applied){applied.push_back(id);Record({0,DialogueChangeKind::ConsequenceApplied,e.session,{}, {},e.context,revision_});}}return applied;}
std::vector<DialogueChange> DialogueService::ChangesSince(std::uint64_t seq)const{std::vector<DialogueChange>out;std::copy_if(changes_.begin(),changes_.end(),std::back_inserter(out),[seq](auto&c){return c.sequence>seq;});return out;}
DialogueSnapshot DialogueService::CaptureSnapshot()const{DialogueSnapshot s;for(const auto&[id,v]:sessions_){(void)id;s.sessions.push_back(v);}for(const auto&[id,v]:consequences_){(void)id;s.consequences.push_back(v);}std::sort(s.sessions.begin(),s.sessions.end(),[](auto&a,auto&b){return a.id<b.id;});std::sort(s.consequences.begin(),s.consequences.end(),[](auto&a,auto&b){return a.id<b.id;});s.session_ids=session_ids_.GetSnapshot();s.consequence_ids=consequence_ids_.GetSnapshot();s.revision=revision_;return s;}
foundation::Result<void> DialogueService::RestoreSnapshot(DialogueSnapshot s){std::unordered_map<ConversationSessionId,ConversationSession,IdHash> sessions;for(auto&v:s.sessions){if(!v.id.IsValid()||!definitions_.contains(v.definition)||sessions.contains(v.id))return foundation::Result<void>::Failure(Error("gameplay.dialogue.restore_invalid","invalid dialogue session snapshot"));sessions.emplace(v.id,std::move(v));}std::unordered_map<DialogueConsequenceExecutionId,DialogueConsequenceExecution,IdHash> consequences;for(auto&v:s.consequences){if(!v.id.IsValid()||!sessions.contains(v.session)||consequences.contains(v.id))return foundation::Result<void>::Failure(Error("gameplay.dialogue.restore_invalid","invalid dialogue consequence snapshot"));consequences.emplace(v.id,std::move(v));}sessions_=std::move(sessions);consequences_=std::move(consequences);session_ids_.Restore(s.session_ids);consequence_ids_.Restore(s.consequence_ids);revision_=s.revision;changes_.clear();next_change_sequence_=1;diagnostics_.active_sessions=0;for(const auto&[id,v]:sessions_){(void)id;if(v.state!=ConversationState::Completed&&v.state!=ConversationState::Interrupted&&v.state!=ConversationState::Failed)++diagnostics_.active_sessions;}diagnostics_.consequences=consequences_.size();diagnostics_.definitions=definitions_.size();return foundation::Result<void>::Success();}
DialogueDiagnostics DialogueService::GetDiagnostics()const noexcept{return diagnostics_;}
void DialogueService::Record(DialogueChange c){c.sequence=next_change_sequence_++;changes_.push_back(std::move(c));}
}
