add_executable(EpidemicGameFrameworkFoundationTests foundation_tests.cpp)
target_link_libraries(EpidemicGameFrameworkFoundationTests PRIVATE EpidemicGameFrameworkFoundation)
epidemic_configure_target(EpidemicGameFrameworkFoundationTests)
epidemic_add_test(EpidemicGameFrameworkFoundationTests)

add_executable(EpidemicGameFrameworkTestUtilitiesTests test_utilities_tests.cpp)
epidemic_configure_target(EpidemicGameFrameworkTestUtilitiesTests)
epidemic_add_test(EpidemicGameFrameworkTestUtilitiesTests)

add_executable(EpidemicGameplayQueriesTests queries_tests.cpp)
target_link_libraries(EpidemicGameplayQueriesTests PRIVATE EpidemicGameplayQueries)
epidemic_configure_target(EpidemicGameplayQueriesTests)
epidemic_add_test(EpidemicGameplayQueriesTests)

add_executable(EpidemicGameplayFactsTests facts_tests.cpp)
target_link_libraries(EpidemicGameplayFactsTests PRIVATE EpidemicGameplayFacts)
epidemic_configure_target(EpidemicGameplayFactsTests)
epidemic_add_test(EpidemicGameplayFactsTests)

add_executable(EpidemicGameplayTimeTests time_tests.cpp)
target_link_libraries(EpidemicGameplayTimeTests PRIVATE EpidemicGameplayTime)
epidemic_configure_target(EpidemicGameplayTimeTests)
epidemic_add_test(EpidemicGameplayTimeTests)

add_executable(EpidemicGameFrameworkCoreIntegrationTests core_integration_tests.cpp)
target_link_libraries(EpidemicGameFrameworkCoreIntegrationTests PRIVATE EpidemicGameFrameworkCoreIntegration)
epidemic_configure_target(EpidemicGameFrameworkCoreIntegrationTests)
epidemic_add_test(EpidemicGameFrameworkCoreIntegrationTests)

add_executable(EpidemicGameFrameworkEntitiesTests entities_tests.cpp)
target_link_libraries(EpidemicGameFrameworkEntitiesTests PRIVATE EpidemicGameFrameworkEntities)
epidemic_configure_target(EpidemicGameFrameworkEntitiesTests)
epidemic_add_test(EpidemicGameFrameworkEntitiesTests)

add_executable(EpidemicGameFrameworkMaterialsTests materials_tests.cpp)
target_link_libraries(EpidemicGameFrameworkMaterialsTests PRIVATE EpidemicGameFrameworkMaterials)
epidemic_configure_target(EpidemicGameFrameworkMaterialsTests)
epidemic_add_test(EpidemicGameFrameworkMaterialsTests)

add_executable(EpidemicGameFrameworkConditionsTests conditions_tests.cpp)
target_link_libraries(EpidemicGameFrameworkConditionsTests PRIVATE EpidemicGameFrameworkConditions)
epidemic_configure_target(EpidemicGameFrameworkConditionsTests)
epidemic_add_test(EpidemicGameFrameworkConditionsTests)

add_executable(EpidemicGameFrameworkEffectsTests effects_tests.cpp)
target_link_libraries(EpidemicGameFrameworkEffectsTests PRIVATE EpidemicGameFrameworkEffects)
epidemic_configure_target(EpidemicGameFrameworkEffectsTests)
epidemic_add_test(EpidemicGameFrameworkEffectsTests)

add_executable(EpidemicGameFrameworkStateIntegrationTests state_integration_tests.cpp)
target_link_libraries(EpidemicGameFrameworkStateIntegrationTests PRIVATE EpidemicGameFrameworkStateIntegration)
epidemic_configure_target(EpidemicGameFrameworkStateIntegrationTests)
epidemic_add_test(EpidemicGameFrameworkStateIntegrationTests)

add_executable(EpidemicGameFrameworkWorldTests world_tests.cpp)
target_link_libraries(EpidemicGameFrameworkWorldTests PRIVATE EpidemicGameFrameworkWorld)
epidemic_configure_target(EpidemicGameFrameworkWorldTests)
epidemic_add_test(EpidemicGameFrameworkWorldTests)

add_executable(EpidemicGameFrameworkEnvironmentTests environment_gameplay_tests.cpp)
target_link_libraries(EpidemicGameFrameworkEnvironmentTests PRIVATE EpidemicGameFrameworkEnvironment)
epidemic_configure_target(EpidemicGameFrameworkEnvironmentTests)
epidemic_add_test(EpidemicGameFrameworkEnvironmentTests)

add_executable(EpidemicGameFrameworkInteractionTests interaction_gameplay_tests.cpp)
target_link_libraries(EpidemicGameFrameworkInteractionTests PRIVATE EpidemicGameFrameworkInteraction)
epidemic_configure_target(EpidemicGameFrameworkInteractionTests)
epidemic_add_test(EpidemicGameFrameworkInteractionTests)

add_executable(EpidemicGameFrameworkWorldIntegrationTests world_integration_tests.cpp)
target_link_libraries(EpidemicGameFrameworkWorldIntegrationTests PRIVATE EpidemicGameFrameworkWorldIntegration)
epidemic_configure_target(EpidemicGameFrameworkWorldIntegrationTests)
epidemic_add_test(EpidemicGameFrameworkWorldIntegrationTests)

add_executable(EpidemicGameFrameworkInteractionTimeIntegrationTests interaction_time_integration_tests.cpp)
target_link_libraries(EpidemicGameFrameworkInteractionTimeIntegrationTests PRIVATE EpidemicGameFrameworkInteractionTimeIntegration)
epidemic_configure_target(EpidemicGameFrameworkInteractionTimeIntegrationTests)
epidemic_add_test(EpidemicGameFrameworkInteractionTimeIntegrationTests)

add_executable(EpidemicGameFrameworkRuntimeBridgeTests runtime_bridge_tests.cpp)
target_link_libraries(EpidemicGameFrameworkRuntimeBridgeTests PRIVATE EpidemicGameFrameworkRuntimeBridge)
epidemic_configure_target(EpidemicGameFrameworkRuntimeBridgeTests)
epidemic_add_test(EpidemicGameFrameworkRuntimeBridgeTests)

add_executable(EpidemicGameFrameworkRandomSupportTests random_support_tests.cpp)
target_link_libraries(EpidemicGameFrameworkRandomSupportTests PRIVATE EpidemicGameFrameworkSupportRandom)
epidemic_configure_target(EpidemicGameFrameworkRandomSupportTests)
epidemic_add_test(EpidemicGameFrameworkRandomSupportTests)

add_executable(EpidemicGameFrameworkProgressionTests progression_tests.cpp)
target_link_libraries(EpidemicGameFrameworkProgressionTests PRIVATE EpidemicGameFrameworkProgression)
epidemic_configure_target(EpidemicGameFrameworkProgressionTests)
epidemic_add_test(EpidemicGameFrameworkProgressionTests)

add_executable(EpidemicGameFrameworkCombatTests combat_tests.cpp)
target_link_libraries(EpidemicGameFrameworkCombatTests PRIVATE EpidemicGameFrameworkCombat)
epidemic_configure_target(EpidemicGameFrameworkCombatTests)
epidemic_add_test(EpidemicGameFrameworkCombatTests)

add_executable(EpidemicGameFrameworkAbilitiesTests abilities_tests.cpp)
target_link_libraries(EpidemicGameFrameworkAbilitiesTests PRIVATE EpidemicGameFrameworkAbilities)
epidemic_configure_target(EpidemicGameFrameworkAbilitiesTests)
epidemic_add_test(EpidemicGameFrameworkAbilitiesTests)

add_executable(EpidemicGameFrameworkLootTests loot_tests.cpp)
target_link_libraries(EpidemicGameFrameworkLootTests PRIVATE EpidemicGameFrameworkLoot)
epidemic_configure_target(EpidemicGameFrameworkLootTests)
epidemic_add_test(EpidemicGameFrameworkLootTests)

add_executable(EpidemicGameFrameworkGameplayIntegrationTests gameplay_integration_tests.cpp)
target_link_libraries(EpidemicGameFrameworkGameplayIntegrationTests PRIVATE EpidemicGameFrameworkGameplayIntegration)
epidemic_configure_target(EpidemicGameFrameworkGameplayIntegrationTests)
epidemic_add_test(EpidemicGameFrameworkGameplayIntegrationTests)

add_executable(EpidemicGameFrameworkTraversalTests traversal_tests.cpp)
target_link_libraries(EpidemicGameFrameworkTraversalTests PRIVATE EpidemicGameFrameworkTraversal)
epidemic_configure_target(EpidemicGameFrameworkTraversalTests)
epidemic_add_test(EpidemicGameFrameworkTraversalTests)

add_executable(EpidemicGameFrameworkNavigationSemanticsTests navigation_semantics_tests.cpp)
target_link_libraries(EpidemicGameFrameworkNavigationSemanticsTests PRIVATE EpidemicGameFrameworkNavigationSemantics)
epidemic_configure_target(EpidemicGameFrameworkNavigationSemanticsTests)
epidemic_add_test(EpidemicGameFrameworkNavigationSemanticsTests)

add_executable(EpidemicGameFrameworkConstructionTests construction_tests.cpp)
target_link_libraries(EpidemicGameFrameworkConstructionTests PRIVATE EpidemicGameFrameworkConstruction)
epidemic_configure_target(EpidemicGameFrameworkConstructionTests)
epidemic_add_test(EpidemicGameFrameworkConstructionTests)

add_executable(EpidemicGameFrameworkTraversalNavigationConstructionIntegrationTests traversal_navigation_construction_integration_tests.cpp)
target_link_libraries(EpidemicGameFrameworkTraversalNavigationConstructionIntegrationTests PRIVATE EpidemicGameFrameworkTraversalNavigationConstructionIntegration)
epidemic_configure_target(EpidemicGameFrameworkTraversalNavigationConstructionIntegrationTests)
epidemic_add_test(EpidemicGameFrameworkTraversalNavigationConstructionIntegrationTests)

add_executable(EpidemicGameFrameworkPerceptionTests perception_tests.cpp)
target_link_libraries(EpidemicGameFrameworkPerceptionTests PRIVATE EpidemicGameFrameworkPerception)
epidemic_configure_target(EpidemicGameFrameworkPerceptionTests)
epidemic_add_test(EpidemicGameFrameworkPerceptionTests)

add_executable(EpidemicGameFrameworkKnowledgeTests knowledge_memory_tests.cpp)
target_link_libraries(EpidemicGameFrameworkKnowledgeTests PRIVATE EpidemicGameFrameworkKnowledge)
epidemic_configure_target(EpidemicGameFrameworkKnowledgeTests)
epidemic_add_test(EpidemicGameFrameworkKnowledgeTests)

add_executable(EpidemicGameFrameworkAITests ai_tests.cpp)
target_link_libraries(EpidemicGameFrameworkAITests PRIVATE EpidemicGameFrameworkAI)
epidemic_configure_target(EpidemicGameFrameworkAITests)
epidemic_add_test(EpidemicGameFrameworkAITests)

add_executable(EpidemicGameFrameworkPerceptionKnowledgeAIIntegrationTests perception_knowledge_ai_integration_tests.cpp)
target_link_libraries(EpidemicGameFrameworkPerceptionKnowledgeAIIntegrationTests PRIVATE EpidemicGameFrameworkPerceptionKnowledgeAIIntegration)
epidemic_configure_target(EpidemicGameFrameworkPerceptionKnowledgeAIIntegrationTests)
epidemic_add_test(EpidemicGameFrameworkPerceptionKnowledgeAIIntegrationTests)

add_executable(EpidemicGameFrameworkOwnershipTests ownership_tests.cpp)
target_link_libraries(EpidemicGameFrameworkOwnershipTests PRIVATE EpidemicGameFrameworkOwnership)
epidemic_configure_target(EpidemicGameFrameworkOwnershipTests)
epidemic_add_test(EpidemicGameFrameworkOwnershipTests)

add_executable(EpidemicGameFrameworkSocietyTests society_tests.cpp)
target_link_libraries(EpidemicGameFrameworkSocietyTests PRIVATE EpidemicGameFrameworkSociety)
epidemic_configure_target(EpidemicGameFrameworkSocietyTests)
epidemic_add_test(EpidemicGameFrameworkSocietyTests)

add_executable(EpidemicGameFrameworkCrimeTests crime_tests.cpp)
target_link_libraries(EpidemicGameFrameworkCrimeTests PRIVATE EpidemicGameFrameworkCrime)
epidemic_configure_target(EpidemicGameFrameworkCrimeTests)
epidemic_add_test(EpidemicGameFrameworkCrimeTests)

add_executable(EpidemicGameFrameworkSocialLegalIntegrationTests social_legal_integration_tests.cpp)
target_link_libraries(EpidemicGameFrameworkSocialLegalIntegrationTests PRIVATE EpidemicGameFrameworkSocialLegalIntegration)
epidemic_configure_target(EpidemicGameFrameworkSocialLegalIntegrationTests)
epidemic_add_test(EpidemicGameFrameworkSocialLegalIntegrationTests)

add_executable(EpidemicGameFrameworkPopulationTests population_tests.cpp)
target_link_libraries(EpidemicGameFrameworkPopulationTests PRIVATE EpidemicGameFrameworkPopulation)
epidemic_configure_target(EpidemicGameFrameworkPopulationTests)
epidemic_add_test(EpidemicGameFrameworkPopulationTests)

add_executable(EpidemicGameFrameworkEncountersTests encounters_tests.cpp)
target_link_libraries(EpidemicGameFrameworkEncountersTests PRIVATE EpidemicGameFrameworkEncounters)
epidemic_configure_target(EpidemicGameFrameworkEncountersTests)
epidemic_add_test(EpidemicGameFrameworkEncountersTests)

add_executable(EpidemicGameFrameworkRolesJobsTests roles_jobs_tests.cpp)
target_link_libraries(EpidemicGameFrameworkRolesJobsTests PRIVATE EpidemicGameFrameworkRolesJobs)
epidemic_configure_target(EpidemicGameFrameworkRolesJobsTests)
epidemic_add_test(EpidemicGameFrameworkRolesJobsTests)

add_executable(EpidemicGameFrameworkNeedsLifeTests needs_life_tests.cpp)
target_link_libraries(EpidemicGameFrameworkNeedsLifeTests PRIVATE EpidemicGameFrameworkNeedsLife)
epidemic_configure_target(EpidemicGameFrameworkNeedsLifeTests)
epidemic_add_test(EpidemicGameFrameworkNeedsLifeTests)

add_executable(EpidemicGameFrameworkPopulationSimulationIntegrationTests population_simulation_integration_tests.cpp)
target_link_libraries(EpidemicGameFrameworkPopulationSimulationIntegrationTests PRIVATE EpidemicGameFrameworkPopulationSimulationIntegration)
epidemic_configure_target(EpidemicGameFrameworkPopulationSimulationIntegrationTests)
epidemic_add_test(EpidemicGameFrameworkPopulationSimulationIntegrationTests)

add_executable(EpidemicGameFrameworkProcessesTests processes_tests.cpp)
target_link_libraries(EpidemicGameFrameworkProcessesTests PRIVATE EpidemicGameFrameworkProcesses)
epidemic_configure_target(EpidemicGameFrameworkProcessesTests)
epidemic_add_test(EpidemicGameFrameworkProcessesTests)

add_executable(EpidemicGameFrameworkResourcesProductionTests resources_production_tests.cpp)
target_link_libraries(EpidemicGameFrameworkResourcesProductionTests PRIVATE EpidemicGameFrameworkResourcesProduction)
epidemic_configure_target(EpidemicGameFrameworkResourcesProductionTests)
epidemic_add_test(EpidemicGameFrameworkResourcesProductionTests)

add_executable(EpidemicGameFrameworkSimulationTests simulation_tests.cpp)
target_link_libraries(EpidemicGameFrameworkSimulationTests PRIVATE EpidemicGameFrameworkSimulation)
epidemic_configure_target(EpidemicGameFrameworkSimulationTests)
epidemic_add_test(EpidemicGameFrameworkSimulationTests)

add_executable(EpidemicGameFrameworkProcessResourceSimulationIntegrationTests process_resource_simulation_integration_tests.cpp)
target_link_libraries(EpidemicGameFrameworkProcessResourceSimulationIntegrationTests PRIVATE EpidemicGameFrameworkProcessResourceSimulationIntegration)
epidemic_configure_target(EpidemicGameFrameworkProcessResourceSimulationIntegrationTests)
epidemic_add_test(EpidemicGameFrameworkProcessResourceSimulationIntegrationTests)

add_executable(EpidemicGameFrameworkNarrativeTests narrative_tests.cpp)
target_link_libraries(EpidemicGameFrameworkNarrativeTests PRIVATE EpidemicGameFrameworkNarrative)
epidemic_configure_target(EpidemicGameFrameworkNarrativeTests)
epidemic_add_test(EpidemicGameFrameworkNarrativeTests)

add_executable(EpidemicGameFrameworkNarrativeChoicesStoryletsTests narrative_choices_storylets_tests.cpp)
target_link_libraries(EpidemicGameFrameworkNarrativeChoicesStoryletsTests PRIVATE EpidemicGameFrameworkNarrative)
epidemic_configure_target(EpidemicGameFrameworkNarrativeChoicesStoryletsTests)
epidemic_add_test(EpidemicGameFrameworkNarrativeChoicesStoryletsTests)

add_executable(EpidemicGameFrameworkNarrativeIntegrationTests narrative_integration_tests.cpp)
target_link_libraries(EpidemicGameFrameworkNarrativeIntegrationTests PRIVATE EpidemicGameFrameworkNarrativeIntegration)
epidemic_configure_target(EpidemicGameFrameworkNarrativeIntegrationTests)
epidemic_add_test(EpidemicGameFrameworkNarrativeIntegrationTests)

add_executable(EpidemicGameFrameworkItemsInventoryTests items_inventory_tests.cpp)
target_link_libraries(EpidemicGameFrameworkItemsInventoryTests PRIVATE EpidemicGameFrameworkItemsInventory)
epidemic_configure_target(EpidemicGameFrameworkItemsInventoryTests)
epidemic_add_test(EpidemicGameFrameworkItemsInventoryTests)

add_executable(EpidemicGameFrameworkEquipmentTests equipment_tests.cpp)
target_link_libraries(EpidemicGameFrameworkEquipmentTests PRIVATE EpidemicGameFrameworkEquipment)
epidemic_configure_target(EpidemicGameFrameworkEquipmentTests)
epidemic_add_test(EpidemicGameFrameworkEquipmentTests)

add_executable(EpidemicGameFrameworkDialogueTests dialogue_tests.cpp)
target_link_libraries(EpidemicGameFrameworkDialogueTests PRIVATE EpidemicGameFrameworkDialogue)
epidemic_configure_target(EpidemicGameFrameworkDialogueTests)
epidemic_add_test(EpidemicGameFrameworkDialogueTests)

add_executable(EpidemicGameFrameworkEconomyTests economy_tests.cpp)
target_link_libraries(EpidemicGameFrameworkEconomyTests PRIVATE EpidemicGameFrameworkEconomy)
epidemic_configure_target(EpidemicGameFrameworkEconomyTests)
epidemic_add_test(EpidemicGameFrameworkEconomyTests)

add_executable(EpidemicGameFrameworkSaveGameTests save_game_tests.cpp)
target_link_libraries(EpidemicGameFrameworkSaveGameTests PRIVATE EpidemicGameFrameworkSaveGame)
epidemic_configure_target(EpidemicGameFrameworkSaveGameTests)
epidemic_add_test(EpidemicGameFrameworkSaveGameTests)

add_executable(EpidemicGameFrameworkResourcesProductionSeparationTests resources_production_separation_tests.cpp)
target_link_libraries(EpidemicGameFrameworkResourcesProductionSeparationTests PRIVATE EpidemicGameFrameworkResourcesProduction)
epidemic_configure_target(EpidemicGameFrameworkResourcesProductionSeparationTests)
epidemic_add_test(EpidemicGameFrameworkResourcesProductionSeparationTests)

add_executable(EpidemicGameFrameworkExtendedGameplayIntegrationTests extended_gameplay_integration_tests.cpp)
target_link_libraries(EpidemicGameFrameworkExtendedGameplayIntegrationTests PRIVATE EpidemicGameFrameworkExtendedGameplayIntegration)
epidemic_configure_target(EpidemicGameFrameworkExtendedGameplayIntegrationTests)
epidemic_add_test(EpidemicGameFrameworkExtendedGameplayIntegrationTests)

add_executable(EpidemicGameFrameworkInteractionEffectsIntegrationTests interaction_effects_integration_tests.cpp)
target_link_libraries(EpidemicGameFrameworkInteractionEffectsIntegrationTests PRIVATE EpidemicGameFrameworkInteractionEffectsIntegration)
epidemic_configure_target(EpidemicGameFrameworkInteractionEffectsIntegrationTests)
epidemic_add_test(EpidemicGameFrameworkInteractionEffectsIntegrationTests)
