set(EPIDEMIC_GAMEFRAMEWORK_BASE_INFRASTRUCTURE_MODULES
    Foundation SupportRandom Queries Facts Time)

set(EPIDEMIC_GAMEFRAMEWORK_RUNTIME_BOUNDARY_MODULES
    RuntimeBridge)

set(EPIDEMIC_GAMEFRAMEWORK_CORE_MODULES
    Foundation SupportRandom Queries Facts Time Entities World Environment Materials Conditions Effects Interaction
    ItemsInventory Equipment Dialogue Economy Combat Abilities Progression Loot Traversal NavigationSemantics Construction
    Perception Knowledge AI Ownership Society Crime Population Encounters RolesJobs NeedsLife Processes ResourcesProduction
    Simulation SaveGame Narrative)

set(EPIDEMIC_GAMEFRAMEWORK_INTEGRATION_MODULES
    Integration StateIntegration GameplayIntegration ExtendedGameplayIntegration WorldIntegration InteractionEffectsIntegration
    InteractionTimeIntegration TraversalNavigationConstructionIntegration PerceptionKnowledgeAIIntegration PopulationSimulationIntegration
    ProcessResourceSimulationIntegration SocialLegalIntegration NarrativeIntegration RuntimeBridge)

set(EPIDEMIC_GAMEFRAMEWORK_ALLOWED_CORE_DEPS Foundation SupportRandom)

set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Foundation EpidemicGameFrameworkFoundation)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_SupportRandom EpidemicGameFrameworkSupportRandom)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Queries EpidemicGameplayQueries)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Facts EpidemicGameplayFacts)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Time EpidemicGameplayTime)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_RuntimeBridge EpidemicGameFrameworkRuntimeBridge)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Entities EpidemicGameFrameworkEntities)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_World EpidemicGameFrameworkWorld)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Environment EpidemicGameFrameworkEnvironment)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Materials EpidemicGameFrameworkMaterials)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Conditions EpidemicGameFrameworkConditions)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Effects EpidemicGameFrameworkEffects)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Interaction EpidemicGameFrameworkInteraction)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_ItemsInventory EpidemicGameFrameworkItemsInventory)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Equipment EpidemicGameFrameworkEquipment)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Dialogue EpidemicGameFrameworkDialogue)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Economy EpidemicGameFrameworkEconomy)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Combat EpidemicGameFrameworkCombat)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Abilities EpidemicGameFrameworkAbilities)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Progression EpidemicGameFrameworkProgression)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Loot EpidemicGameFrameworkLoot)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Traversal EpidemicGameFrameworkTraversal)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_NavigationSemantics EpidemicGameFrameworkNavigationSemantics)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Construction EpidemicGameFrameworkConstruction)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Perception EpidemicGameFrameworkPerception)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Knowledge EpidemicGameFrameworkKnowledge)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_AI EpidemicGameFrameworkAI)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Ownership EpidemicGameFrameworkOwnership)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Society EpidemicGameFrameworkSociety)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Crime EpidemicGameFrameworkCrime)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Population EpidemicGameFrameworkPopulation)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Encounters EpidemicGameFrameworkEncounters)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_RolesJobs EpidemicGameFrameworkRolesJobs)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_NeedsLife EpidemicGameFrameworkNeedsLife)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Processes EpidemicGameFrameworkProcesses)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_ResourcesProduction EpidemicGameFrameworkResourcesProduction)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Simulation EpidemicGameFrameworkSimulation)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_SaveGame EpidemicGameFrameworkSaveGame)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Narrative EpidemicGameFrameworkNarrative)

set(EPIDEMIC_GAMEFRAMEWORK_TARGET_Integration EpidemicGameFrameworkCoreIntegration)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_StateIntegration EpidemicGameFrameworkStateIntegration)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_GameplayIntegration EpidemicGameFrameworkGameplayIntegration)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_ExtendedGameplayIntegration EpidemicGameFrameworkExtendedGameplayIntegration)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_WorldIntegration EpidemicGameFrameworkWorldIntegration)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_InteractionEffectsIntegration EpidemicGameFrameworkInteractionEffectsIntegration)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_InteractionTimeIntegration EpidemicGameFrameworkInteractionTimeIntegration)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_TraversalNavigationConstructionIntegration EpidemicGameFrameworkTraversalNavigationConstructionIntegration)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_PerceptionKnowledgeAIIntegration EpidemicGameFrameworkPerceptionKnowledgeAIIntegration)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_PopulationSimulationIntegration EpidemicGameFrameworkPopulationSimulationIntegration)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_ProcessResourceSimulationIntegration EpidemicGameFrameworkProcessResourceSimulationIntegration)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_SocialLegalIntegration EpidemicGameFrameworkSocialLegalIntegration)
set(EPIDEMIC_GAMEFRAMEWORK_TARGET_NarrativeIntegration EpidemicGameFrameworkNarrativeIntegration)

get_filename_component(EPIDEMIC_GAMEFRAMEWORK_ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)

foreach(_module IN LISTS EPIDEMIC_GAMEFRAMEWORK_BASE_INFRASTRUCTURE_MODULES)
    set(EPIDEMIC_GAMEFRAMEWORK_MODULE_ROOT_${_module} "${EPIDEMIC_GAMEFRAMEWORK_ROOT}/BaseInfrastructure/${_module}")
endforeach()
foreach(_module IN LISTS EPIDEMIC_GAMEFRAMEWORK_RUNTIME_BOUNDARY_MODULES)
    set(EPIDEMIC_GAMEFRAMEWORK_MODULE_ROOT_${_module} "${EPIDEMIC_GAMEFRAMEWORK_ROOT}/RuntimeBoundary/${_module}")
endforeach()
foreach(_module IN LISTS EPIDEMIC_GAMEFRAMEWORK_CORE_MODULES)
    if(NOT DEFINED EPIDEMIC_GAMEFRAMEWORK_MODULE_ROOT_${_module})
        set(EPIDEMIC_GAMEFRAMEWORK_MODULE_ROOT_${_module} "${EPIDEMIC_GAMEFRAMEWORK_ROOT}/GameplayWorldStateOwners/${_module}")
    endif()
endforeach()
foreach(_module IN LISTS EPIDEMIC_GAMEFRAMEWORK_INTEGRATION_MODULES)
    if(NOT DEFINED EPIDEMIC_GAMEFRAMEWORK_MODULE_ROOT_${_module})
        set(EPIDEMIC_GAMEFRAMEWORK_MODULE_ROOT_${_module} "${EPIDEMIC_GAMEFRAMEWORK_ROOT}/IntegrationLayer/${_module}")
    endif()
endforeach()

function(epidemic_validate_framework_architecture)
    set(_all_modules ${EPIDEMIC_GAMEFRAMEWORK_CORE_MODULES} ${EPIDEMIC_GAMEFRAMEWORK_INTEGRATION_MODULES})
    set(_all_targets)
    foreach(_module IN LISTS _all_modules)
        if(DEFINED EPIDEMIC_GAMEFRAMEWORK_TARGET_${_module})
            list(APPEND _all_targets "${EPIDEMIC_GAMEFRAMEWORK_TARGET_${_module}}")
        endif()
    endforeach()

    set(_foundation_target "${EPIDEMIC_GAMEFRAMEWORK_TARGET_Foundation}")
    if(TARGET "${_foundation_target}")
        get_target_property(_foundation_links "${_foundation_target}" LINK_LIBRARIES)
        get_target_property(_foundation_interface_links "${_foundation_target}" INTERFACE_LINK_LIBRARIES)
        foreach(_dep IN LISTS _foundation_links _foundation_interface_links)
            list(FIND _all_targets "${_dep}" _foundation_dep_index)
            if(_foundation_dep_index GREATER -1 AND NOT _dep STREQUAL "${_foundation_target}")
                message(FATAL_ERROR "${_foundation_target} must not link EngineFramework target '${_dep}'.")
            endif()
        endforeach()
    endif()

    foreach(_module IN LISTS EPIDEMIC_GAMEFRAMEWORK_CORE_MODULES)
        set(_target "${EPIDEMIC_GAMEFRAMEWORK_TARGET_${_module}}")
        if(TARGET "${_target}")
            get_target_property(_links "${_target}" LINK_LIBRARIES)
            get_target_property(_interface_links "${_target}" INTERFACE_LINK_LIBRARIES)
            foreach(_dep IN LISTS _links _interface_links)
                list(FIND _all_targets "${_dep}" _dep_index)
                if(_dep_index GREATER -1)
                    set(_allowed FALSE)
                    foreach(_allowed_module IN LISTS EPIDEMIC_GAMEFRAMEWORK_ALLOWED_CORE_DEPS)
                        if(_dep STREQUAL "${EPIDEMIC_GAMEFRAMEWORK_TARGET_${_allowed_module}}")
                            set(_allowed TRUE)
                        endif()
                    endforeach()
                    if(_dep STREQUAL "${_target}")
                        set(_allowed TRUE)
                    endif()
                    if(NOT _allowed)
                        message(FATAL_ERROR "${_target} links gameplay module '${_dep}' without central allowlist permission.")
                    endif()
                endif()
            endforeach()
        endif()

        set(_module_root "${EPIDEMIC_GAMEFRAMEWORK_MODULE_ROOT_${_module}}")
        file(GLOB_RECURSE _module_sources CONFIGURE_DEPENDS
            "${_module_root}/include/*.h"
            "${_module_root}/src/*.cpp")
        foreach(_file IN LISTS _module_sources)
            file(READ "${_file}" _content)
            foreach(_other IN LISTS _all_modules)
                if(NOT _other STREQUAL _module)
                    list(FIND EPIDEMIC_GAMEFRAMEWORK_ALLOWED_CORE_DEPS "${_other}" _allow_index)
                    if(_allow_index EQUAL -1 AND _content MATCHES "Epidemic/GameFramework/${_other}/")
                        message(FATAL_ERROR "${_module} includes GameFramework/${_other} from ${_file} without central allowlist permission.")
                    endif()
                endif()
            endforeach()
        endforeach()
    endforeach()
endfunction()