#include "Epidemic/GameFramework/Ownership/ownership.h"
#include "Epidemic/Foundation/error.h"
#include <utility>
#include <iterator>

namespace epidemic::gameplay::ownership
{
namespace{foundation::Error Error(std::string_view c,std::string_view m){return foundation::Error::Create(c,m);} }
OwnershipRecord* OwnershipService::FindMutableOwnership(OwnershipRecordId id) noexcept{auto it=records_.find(id);return it==records_.end()?nullptr:&it->second;}
foundation::Result<OwnershipRecordId> OwnershipService::AssignOwnership(OwnershipRecord r){if(!r.property.IsValid()||!r.owner.IsValid())return foundation::Result<OwnershipRecordId>::Failure(Error("gameplay.ownership.invalid_record","invalid ownership record"));if(!r.id.IsValid())r.id=OwnershipRecordId{ownership_ids_.Next()};if(records_.contains(r.id))return foundation::Result<OwnershipRecordId>::Failure(Error("gameplay.ownership.duplicate_record","duplicate ownership record"));Bump();r.revision=revision_;auto id=r.id;records_.emplace(id,r);Record({0,OwnershipChangeKind::OwnershipAssigned,r.property,{},r.owner,{}, {},revision_});return foundation::Result<OwnershipRecordId>::Success(id);} 
foundation::Result<void> OwnershipService::RemoveOwnership(OwnershipRecordId id,GameplayContext c){auto it=records_.find(id);if(it==records_.end())return foundation::Result<void>::Failure(Error("gameplay.ownership.record_missing","ownership record missing"));auto property=it->second.property;auto owner=it->second.owner;records_.erase(it);Bump();Record({0,OwnershipChangeKind::OwnershipRemoved,property,{},owner,{},c,revision_});return foundation::Result<void>::Success();}
foundation::Result<void> OwnershipService::TransferOwnership(TransferOwnershipRequest q){if(!q.property.IsValid()||!q.to_owner.IsValid())return foundation::Result<void>::Failure(Error("gameplay.ownership.invalid_transfer","invalid transfer"));auto* current=const_cast<OwnershipRecord*>(GetOwner(q.property));if(!current){OwnershipRecord r;r.property=q.property;r.owner=q.to_owner;r.strength=q.reason==TransferReason::Theft?OwnershipStrength::Stolen:OwnershipStrength::Owned;auto added=AssignOwnership(r);if(!added)return foundation::Result<void>::Failure(std::move(added.GetError()));return foundation::Result<void>::Success();}if(q.from_owner.IsValid()&&current->owner!=q.from_owner)return foundation::Result<void>::Failure(Error("gameplay.ownership.transfer_owner_mismatch","transfer owner mismatch"));Bump();current->owner=q.to_owner;current->strength=q.reason==TransferReason::Theft?OwnershipStrength::Stolen:OwnershipStrength::Owned;current->revision=revision_;++diagnostics_.ownership_transfers;Record({0,OwnershipChangeKind::OwnershipTransferred,q.property,{},q.to_owner,{},q.context,revision_});return foundation::Result<void>::Success();}
foundation::Result<PermissionGrantId> OwnershipService::GrantPermission(PermissionGrant g){if(!g.subject.IsValid()||!g.property.IsValid()||!g.right.IsValid())return foundation::Result<PermissionGrantId>::Failure(Error("gameplay.ownership.invalid_grant","invalid permission grant"));if(!g.id.IsValid())g.id=PermissionGrantId{grant_ids_.Next()};if(grants_.contains(g.id))return foundation::Result<PermissionGrantId>::Failure(Error("gameplay.ownership.duplicate_grant","duplicate permission grant"));Bump();g.revision=revision_;auto id=g.id;grants_.emplace(id,g);Record({0,OwnershipChangeKind::PermissionGranted,g.property,g.subject,{},g.right,{},revision_});return foundation::Result<PermissionGrantId>::Success(id);} 
foundation::Result<void> OwnershipService::RevokePermission(PermissionGrantId id,GameplayContext c){auto it=grants_.find(id);if(it==grants_.end())return foundation::Result<void>::Failure(Error("gameplay.ownership.grant_missing","permission grant missing"));auto copy=it->second;grants_.erase(it);Bump();Record({0,OwnershipChangeKind::PermissionRevoked,copy.property,copy.subject,{},copy.right,c,revision_});return foundation::Result<void>::Success();}
foundation::Result<AccessRuleId> OwnershipService::AddAccessRule(AccessRule r){if(!r.property.IsValid()||!r.right.IsValid())return foundation::Result<AccessRuleId>::Failure(Error("gameplay.ownership.invalid_rule","invalid access rule"));if(!r.id.IsValid())r.id=AccessRuleId{rule_ids_.Next()};if(rules_.contains(r.id))return foundation::Result<AccessRuleId>::Failure(Error("gameplay.ownership.duplicate_rule","duplicate access rule"));Bump();r.revision=revision_;auto id=r.id;rules_.emplace(id,r);Record({0,OwnershipChangeKind::AccessRuleAdded,r.property,r.required_subject,{},r.right,{},revision_});return foundation::Result<AccessRuleId>::Success(id);} 
foundation::Result<PropertyClaimId> OwnershipService::CreateClaim(PropertyClaim c){if(!c.property.IsValid()||!c.claimant.IsValid())return foundation::Result<PropertyClaimId>::Failure(Error("gameplay.ownership.invalid_claim","invalid property claim"));if(!c.id.IsValid())c.id=PropertyClaimId{claim_ids_.Next()};if(claims_.contains(c.id))return foundation::Result<PropertyClaimId>::Failure(Error("gameplay.ownership.duplicate_claim","duplicate claim"));Bump();c.revision=revision_;auto id=c.id;claims_.emplace(id,c);++diagnostics_.claim_conflicts;Record({0,OwnershipChangeKind::PropertyClaimCreated,c.property,c.claimant,{}, {},{},revision_});return foundation::Result<PropertyClaimId>::Success(id);} 
foundation::Result<void> OwnershipService::ResolveClaim(PropertyClaimId id,GameplayContext c){auto it=claims_.find(id);if(it==claims_.end())return foundation::Result<void>::Failure(Error("gameplay.ownership.claim_missing","claim missing"));auto copy=it->second;claims_.erase(it);Bump();Record({0,OwnershipChangeKind::PropertyClaimResolved,copy.property,copy.claimant,{}, {},c,revision_});return foundation::Result<void>::Success();}
OwnershipPermissionResult OwnershipService::EvaluatePermission(OwnershipPermissionQuery q) const{++diagnostics_.permission_queries;OwnershipPermissionResult out;out.revision=revision_;if(!q.actor.IsValid()||!q.property.IsValid()||!q.right.IsValid()){out.decision=PermissionDecision::Unknown;return out;}auto owner=GetOwner(q.property);if(owner)out.effective_owner=owner->owner;if(owner&&owner->owner==q.actor){out.decision=PermissionDecision::Allowed;return out;}auto rules=FindAccessRules(q.property);std::sort(rules.begin(),rules.end(),[](const auto&a,const auto&b){if(a.priority!=b.priority)return a.priority>b.priority;return a.id<b.id;});for(const auto& r:rules){if(r.right!=q.right)continue;if(r.required_subject.IsValid()&&r.required_subject!=q.actor)continue;switch(r.decision){case AccessDecision::Allow:case AccessDecision::Public:out.decision=PermissionDecision::Allowed;return out;case AccessDecision::Deny:case AccessDecision::Private:++diagnostics_.denied_permissions;out.decision=PermissionDecision::Denied;return out;case AccessDecision::TrespassIfViolated:++diagnostics_.denied_permissions;out.decision=PermissionDecision::Trespass;return out;case AccessDecision::CrimeIfViolated:++diagnostics_.crime_candidate_permissions;out.decision=PermissionDecision::CrimeCandidate;return out;default:break;}}
for(const auto& [id,g]:grants_){(void)id;if(g.subject==q.actor&&g.property==q.property&&g.right==q.right){out.decision=PermissionDecision::Allowed;return out;}}
out.decision=owner?PermissionDecision::CrimeCandidate:PermissionDecision::NotApplicable;if(out.decision==PermissionDecision::CrimeCandidate)++diagnostics_.crime_candidate_permissions;return out;}
const OwnershipRecord* OwnershipService::GetOwner(GameplayObjectRef property) const noexcept{const OwnershipRecord* best=nullptr;for(const auto&[id,r]:records_){(void)id;if(r.property==property&&(r.strength==OwnershipStrength::Owned||r.strength==OwnershipStrength::Public||r.strength==OwnershipStrength::Claimed||r.strength==OwnershipStrength::Stolen)){if(!best||r.id<best->id)best=&r;}}return best;}
std::vector<OwnershipRecord> OwnershipService::GetOwnershipRecords(GameplayObjectRef p) const{std::vector<OwnershipRecord> out;for(const auto&[id,r]:records_){(void)id;if(r.property==p)out.push_back(r);}std::sort(out.begin(),out.end(),[](auto&a,auto&b){return a.id<b.id;});return out;}
std::vector<OwnershipRecord> OwnershipService::FindPropertiesOwnedBy(GameplayObjectRef o) const{std::vector<OwnershipRecord> out;for(const auto&[id,r]:records_){(void)id;if(r.owner==o)out.push_back(r);}std::sort(out.begin(),out.end(),[](auto&a,auto&b){if(a.property!=b.property)return a.property<b.property;return a.id<b.id;});return out;}
std::vector<PermissionGrant> OwnershipService::FindPermissions(GameplayObjectRef s) const{std::vector<PermissionGrant> out;for(const auto&[id,g]:grants_){(void)id;if(g.subject==s)out.push_back(g);}std::sort(out.begin(),out.end(),[](auto&a,auto&b){return a.id<b.id;});return out;}
std::vector<PropertyClaim> OwnershipService::FindClaims(GameplayObjectRef p) const{std::vector<PropertyClaim> out;for(const auto&[id,c]:claims_){(void)id;if(c.property==p)out.push_back(c);}std::sort(out.begin(),out.end(),[](auto&a,auto&b){return a.id<b.id;});return out;}
std::vector<AccessRule> OwnershipService::FindAccessRules(GameplayObjectRef p) const{std::vector<AccessRule> out;for(const auto&[id,r]:rules_){(void)id;if(r.property==p)out.push_back(r);}std::sort(out.begin(),out.end(),[](auto&a,auto&b){if(a.priority!=b.priority)return a.priority>b.priority;return a.id<b.id;});return out;}
std::vector<OwnershipChange> OwnershipService::ChangesSince(std::uint64_t seq) const{std::vector<OwnershipChange> out;std::copy_if(changes_.begin(),changes_.end(),std::back_inserter(out),[seq](auto&c){return c.sequence>seq;});return out;}
OwnershipSnapshot OwnershipService::CaptureSnapshot() const{OwnershipSnapshot s;for(const auto&[id,r]:records_){(void)id;s.records.push_back(r);}for(const auto&[id,g]:grants_){(void)id;s.grants.push_back(g);}for(const auto&[id,r]:rules_){(void)id;s.rules.push_back(r);}for(const auto&[id,c]:claims_){(void)id;s.claims.push_back(c);}std::sort(s.records.begin(),s.records.end(),[](auto&a,auto&b){return a.id<b.id;});std::sort(s.grants.begin(),s.grants.end(),[](auto&a,auto&b){return a.id<b.id;});std::sort(s.rules.begin(),s.rules.end(),[](auto&a,auto&b){return a.id<b.id;});std::sort(s.claims.begin(),s.claims.end(),[](auto&a,auto&b){return a.id<b.id;});s.ownership_ids=ownership_ids_.GetSnapshot();s.grant_ids=grant_ids_.GetSnapshot();s.rule_ids=rule_ids_.GetSnapshot();s.claim_ids=claim_ids_.GetSnapshot();s.revision=revision_;return s;}
foundation::Result<void> OwnershipService::RestoreSnapshot(OwnershipSnapshot s){records_.clear();grants_.clear();rules_.clear();claims_.clear();for(auto&r:s.records){if(!r.id.IsValid()||!r.property.IsValid()||!r.owner.IsValid())return foundation::Result<void>::Failure(Error("gameplay.ownership.restore_invalid","invalid ownership snapshot"));records_[r.id]=r;}for(auto&g:s.grants){if(!g.id.IsValid())return foundation::Result<void>::Failure(Error("gameplay.ownership.restore_invalid","invalid grant snapshot"));grants_[g.id]=g;}for(auto&r:s.rules){if(!r.id.IsValid())return foundation::Result<void>::Failure(Error("gameplay.ownership.restore_invalid","invalid rule snapshot"));rules_[r.id]=r;}for(auto&c:s.claims){if(!c.id.IsValid())return foundation::Result<void>::Failure(Error("gameplay.ownership.restore_invalid","invalid claim snapshot"));claims_[c.id]=c;}ownership_ids_.Restore(s.ownership_ids);grant_ids_.Restore(s.grant_ids);rule_ids_.Restore(s.rule_ids);claim_ids_.Restore(s.claim_ids);revision_=s.revision;changes_.clear();next_change_sequence_=1;return foundation::Result<void>::Success();}
OwnershipDiagnostics OwnershipService::GetDiagnostics() const noexcept{auto d=diagnostics_;d.ownership_records=records_.size();d.permission_grants=grants_.size();d.access_rules=rules_.size();d.property_claims=claims_.size();return d;}
void OwnershipService::Record(OwnershipChange c){c.sequence=next_change_sequence_++;changes_.push_back(c);} 
} // namespace epidemic::gameplay::ownership
