include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/ProductionSourceExtensions.cmake")

set(EPIDEMIC_ARCH_RUNTIME_MAJOR_ALLOWED_DEPENDENCIES
    EpidemicRuntimeFoundation)

set(EPIDEMIC_ARCH_RUNTIME_BOUNDARY_ALLOWED_RUNTIME_DEPENDENCIES
    EpidemicRuntimeWorld
    EpidemicRuntimePhysics
    EpidemicRuntimeEnvironment
    EpidemicRuntimeNavigation)

set(EPIDEMIC_ARCH_RUNTIME_BOUNDARY_ALLOWED_RUNTIME_INCLUDE_PREFIXES
    Epidemic/Runtime/World/
    Epidemic/Runtime/Physics/
    Epidemic/Runtime/Environment/
    Epidemic/Runtime/Navigation/)

set(EPIDEMIC_ARCH_INTEGRATION_RUNTIME_LINK_ALLOWLIST
    "EpidemicGameFrameworkCoreIntegration:EpidemicRuntimeTime")

set(EPIDEMIC_ARCH_INTEGRATION_RUNTIME_INCLUDE_ALLOWLIST
    "EngineFramework/IntegrationLayer/Integration/include/Epidemic/GameFramework/Integration/core_adapters.h:Epidemic/Runtime/Time/time_runtime.h")

function(_epidemic_collect_targets directory out_var)
    get_property(_targets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
    get_property(_children DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
    foreach(_child IN LISTS _children)
        _epidemic_collect_targets("${_child}" _child_targets)
        list(APPEND _targets ${_child_targets})
    endforeach()
    set(${out_var} "${_targets}" PARENT_SCOPE)
endfunction()

function(_epidemic_allowlist_pair_contains allowlist left right out_var)
    set(_allowed OFF)
    foreach(_entry IN LISTS ${allowlist})
        string(REPLACE ":" ";" _parts "${_entry}")
        list(GET _parts 0 _allowed_left)
        list(GET _parts 1 _allowed_right)
        if("${left}" STREQUAL "${_allowed_left}" AND "${right}" STREQUAL "${_allowed_right}")
            set(_allowed ON)
            break()
        endif()
    endforeach()
    set(${out_var} "${_allowed}" PARENT_SCOPE)
endfunction()

function(_epidemic_list_contains values item out_var)
    set(_found OFF)
    foreach(_value IN LISTS ${values})
        if("${item}" STREQUAL "${_value}")
            set(_found ON)
            break()
        endif()
    endforeach()
    set(${out_var} "${_found}" PARENT_SCOPE)
endfunction()

function(_epidemic_normalize_link_dependency dependency out_var)
    set(_normalized "${dependency}")
    if("${_normalized}" MATCHES "^\\$<LINK_ONLY:([^>]+)>$")
        set(_normalized "${CMAKE_MATCH_1}")
    endif()
    set(${out_var} "${_normalized}" PARENT_SCOPE)
endfunction()

function(_epidemic_resolve_target target out_var)
    set(_resolved "${target}")
    if(TARGET "${_resolved}")
        get_target_property(_aliased "${_resolved}" ALIASED_TARGET)
        if(_aliased)
            set(_resolved "${_aliased}")
        endif()
    endif()
    set(${out_var} "${_resolved}" PARENT_SCOPE)
endfunction()

function(_epidemic_collect_reachable_targets target visited path out_var)
    _epidemic_resolve_target("${target}" _target)
    if("${_target}" IN_LIST visited OR NOT TARGET "${_target}")
        set(${out_var} "" PARENT_SCOPE)
        return()
    endif()
    list(APPEND visited "${_target}")
    get_target_property(_direct "${_target}" LINK_LIBRARIES)
    get_target_property(_public "${_target}" INTERFACE_LINK_LIBRARIES)
    set(_reachable)
    foreach(_dependency IN LISTS _direct _public)
        _epidemic_normalize_link_dependency("${_dependency}" _normalized)
        _epidemic_resolve_target("${_normalized}" _resolved)
        if(NOT TARGET "${_resolved}")
            continue()
        endif()
        set(_dependency_path "${path} -> ${_resolved}")
        list(APPEND _reachable "${_resolved}|${_dependency_path}")
        _epidemic_collect_reachable_targets("${_resolved}" "${visited}" "${_dependency_path}" _nested)
        list(APPEND _reachable ${_nested})
    endforeach()
    list(REMOVE_DUPLICATES _reachable)
    set(${out_var} "${_reachable}" PARENT_SCOPE)
endfunction()

function(_epidemic_extract_includes content out_var)
    string(REGEX MATCHALL "#[ \t]*include[ \t]*[<\"][^>\"\r\n]+[>\"]" _directives "${content}")
    set(_includes)
    foreach(_directive IN LISTS _directives)
        string(REGEX REPLACE ".*[<\"]([^>\"]+)[>\"].*" "\\1" _include "${_directive}")
        list(APPEND _includes "${_include}")
    endforeach()
    set(${out_var} "${_includes}" PARENT_SCOPE)
endfunction()

function(_epidemic_include_has_allowed_prefix include prefixes out_var)
    set(_allowed OFF)
    foreach(_prefix IN LISTS ${prefixes})
        string(FIND "${include}" "${_prefix}" _prefix_position)
        if(_prefix_position EQUAL 0)
            set(_allowed ON)
            break()
        endif()
    endforeach()
    set(${out_var} "${_allowed}" PARENT_SCOPE)
endfunction()

function(_epidemic_target_rejects target pattern rule)
    _epidemic_collect_reachable_targets("${target}" "" "${target}" _reachable)
    foreach(_entry IN LISTS _reachable)
        string(REPLACE "|" ";" _parts "${_entry}")
        list(GET _parts 0 _dependency)
        list(GET _parts 1 _path)
        if("${_dependency}" MATCHES "${pattern}")
            message(FATAL_ERROR "${target} violates ${rule}: ${_path}")
        endif()
    endforeach()
endfunction()

function(_epidemic_reject_unapproved_reachable target pattern allowlist rule)
    _epidemic_collect_reachable_targets("${target}" "" "${target}" _reachable)
    foreach(_entry IN LISTS _reachable)
        string(REPLACE "|" ";" _parts "${_entry}")
        list(GET _parts 0 _dependency)
        list(GET _parts 1 _path)
        if("${_dependency}" MATCHES "${pattern}" AND NOT "${_dependency}" IN_LIST ${allowlist})
            message(FATAL_ERROR "${target} violates ${rule}: ${_path}")
        endif()
    endforeach()
endfunction()

function(_epidemic_scan root pattern rule)
    if(NOT EXISTS "${root}")
        return()
    endif()
    file(GLOB_RECURSE _all_files CONFIGURE_DEPENDS "${root}/*")
    set(_files)
    foreach(_file IN LISTS _all_files)
        if(IS_DIRECTORY "${_file}")
            continue()
        endif()
        get_filename_component(_extension "${_file}" LAST_EXT)
        if(NOT _extension IN_LIST EPIDEMIC_PRODUCTION_CXX_EXTENSIONS AND
           NOT _extension IN_LIST EPIDEMIC_PRODUCTION_ANCILLARY_EXTENSIONS)
            message(FATAL_ERROR "Unknown production file extension '${_extension}' requires registry review: ${_file}")
        endif()
        if(_extension IN_LIST EPIDEMIC_PRODUCTION_CXX_EXTENSIONS)
            list(APPEND _files "${_file}")
        endif()
    endforeach()
    foreach(_file IN LISTS _files)
        file(TO_CMAKE_PATH "${_file}" _normalized_file)
        if(_normalized_file MATCHES "/(Apps|Tests|tests|DevelopmentInfrastructure)/")
            continue()
        endif()
        file(READ "${_file}" _content)
        if(_content MATCHES "${pattern}")
            message(FATAL_ERROR "${rule}: ${_file}")
        endif()
        if(_content MATCHES "#[ \t]*include[^\r\n]*\\.\\.")
            message(FATAL_ERROR "Production source uses a private relative include: ${_file}")
        endif()
    endforeach()
endfunction()

function(epidemic_validate_architecture_freeze)
    _epidemic_collect_targets("${PROJECT_SOURCE_DIR}" _targets)
    foreach(_target IN LISTS _targets)
        get_target_property(_type "${_target}" TYPE)
        if(NOT _type MATCHES "^(STATIC|SHARED|MODULE|INTERFACE|OBJECT)_LIBRARY$")
            continue()
        endif()
        get_target_property(_source "${_target}" SOURCE_DIR)
        file(RELATIVE_PATH _relative "${PROJECT_SOURCE_DIR}" "${_source}")
        _epidemic_scan_generated_target_sources("${_target}" "${_relative}")

        if(_relative MATCHES "^EngineBase/" AND NOT _relative MATCHES "^EngineBase/(Tests|Apps)/")
            _epidemic_target_rejects("${_target}" "Epidemic(Runtime|GameFramework|Gameplay)"
                "EngineBase must not depend on Runtime or Framework")
        elseif(_relative MATCHES "^EngineRuntime/" AND NOT _relative MATCHES "^EngineRuntime/(Tests|.*/tests)/")
            _epidemic_target_rejects("${_target}" "Epidemic(GameFramework|Gameplay)"
                "EngineRuntime must not depend on Framework")
            if(NOT _relative MATCHES "^EngineRuntime/(RuntimeFoundation|Support)(/|$)")
                _epidemic_reject_unapproved_reachable(
                    "${_target}" "EpidemicRuntime" EPIDEMIC_ARCH_RUNTIME_MAJOR_ALLOWED_DEPENDENCIES
                    "links an unapproved Runtime major")
            endif()
        elseif(_relative MATCHES "^EngineFramework/(BaseInfrastructure|GameplayWorldStateOwners)/")
            _epidemic_target_rejects("${_target}" "EpidemicRuntime"
                "Framework core must use an approved Runtime boundary")
        elseif(_relative MATCHES "^EngineFramework/IntegrationLayer/")
            _epidemic_collect_reachable_targets("${_target}" "" "${_target}" _reachable)
            foreach(_entry IN LISTS _reachable)
                string(REPLACE "|" ";" _parts "${_entry}")
                list(GET _parts 0 _normalized_dependency)
                list(GET _parts 1 _path)
                if("${_normalized_dependency}" MATCHES "EpidemicRuntime" AND
                   NOT "${_normalized_dependency}" STREQUAL "EpidemicRuntimeFoundation")
                    string(REPLACE " -> " ";" _path_targets "${_path}")
                    list(LENGTH _path_targets _path_length)
                    math(EXPR _boundary_index "${_path_length} - 2")
                    list(GET _path_targets ${_boundary_index} _boundary_target)
                    _epidemic_allowlist_pair_contains(
                        EPIDEMIC_ARCH_INTEGRATION_RUNTIME_LINK_ALLOWLIST
                        "${_boundary_target}"
                        "${_normalized_dependency}"
                        _allowed_integration_runtime_link)
                    if(NOT _allowed_integration_runtime_link)
                        message(FATAL_ERROR "${_target} has unapproved Runtime dependency: ${_path}")
                    endif()
                endif()
            endforeach()
        elseif(_relative MATCHES "^EngineFramework/RuntimeBoundary/")
            _epidemic_collect_reachable_targets("${_target}" "" "${_target}" _reachable)
            foreach(_entry IN LISTS _reachable)
                string(REPLACE "|" ";" _parts "${_entry}")
                list(GET _parts 0 _normalized_dependency)
                list(GET _parts 1 _path)
                if("${_normalized_dependency}" MATCHES "EpidemicRuntime" AND
                   NOT "${_normalized_dependency}" STREQUAL "EpidemicRuntimeFoundation")
                    _epidemic_list_contains(
                        EPIDEMIC_ARCH_RUNTIME_BOUNDARY_ALLOWED_RUNTIME_DEPENDENCIES
                        "${_normalized_dependency}"
                        _allowed_runtime_boundary_link)
                    if(NOT _allowed_runtime_boundary_link)
                        message(FATAL_ERROR "${_target} has unapproved boundary dependency: ${_path}")
                    endif()
                endif()
            endforeach()
        endif()
    endforeach()

    _epidemic_scan("${PROJECT_SOURCE_DIR}/EngineBase" "Epidemic/(Runtime|GameFramework)/"
        "EngineBase source references an upper layer")
    _epidemic_scan("${PROJECT_SOURCE_DIR}/EngineRuntime" "Epidemic/GameFramework/"
        "EngineRuntime source references Framework")
    _epidemic_scan("${PROJECT_SOURCE_DIR}/EngineFramework/BaseInfrastructure"
        "Epidemic/(Runtime|Platform|RHI|RHI_D3D11)/" "Framework infrastructure bypasses a boundary")
    _epidemic_scan("${PROJECT_SOURCE_DIR}/EngineFramework/GameplayWorldStateOwners"
        "Epidemic/(Runtime|Platform|RHI|RHI_D3D11)/" "Framework owner bypasses a boundary")

    if(EPIDEMIC_BUILD_FRAMEWORK)
        file(GLOB_RECURSE _integration CONFIGURE_DEPENDS
            "${PROJECT_SOURCE_DIR}/EngineFramework/IntegrationLayer/*/include/*.h"
            "${PROJECT_SOURCE_DIR}/EngineFramework/IntegrationLayer/*/src/*.h"
            "${PROJECT_SOURCE_DIR}/EngineFramework/IntegrationLayer/*/src/*.cpp")
        foreach(_file IN LISTS _integration)
            file(READ "${_file}" _content)
            file(TO_CMAKE_PATH "${_file}" _normalized)
            file(RELATIVE_PATH _relative_file "${PROJECT_SOURCE_DIR}" "${_normalized}")
            _epidemic_extract_includes("${_content}" _includes)
            foreach(_include IN LISTS _includes)
                if(NOT "${_include}" MATCHES "^Epidemic/Runtime/")
                    continue()
                endif()
                set(_allowed_integration_runtime_include OFF)
                foreach(_entry IN LISTS EPIDEMIC_ARCH_INTEGRATION_RUNTIME_INCLUDE_ALLOWLIST)
                    string(REPLACE ":" ";" _parts "${_entry}")
                    list(GET _parts 0 _allowed_file)
                    list(GET _parts 1 _allowed_include)
                    if("${_relative_file}" STREQUAL "${_allowed_file}" AND
                       "${_include}" STREQUAL "${_allowed_include}")
                        set(_allowed_integration_runtime_include ON)
                        break()
                    endif()
                endforeach()
                if(NOT _allowed_integration_runtime_include)
                    message(FATAL_ERROR "Integration source has unapproved Runtime include ${_include}: ${_file}")
                endif()
            endforeach()
            if(_content MATCHES "/src/" OR _content MATCHES "#[ \t]*include[^\r\n]*\\.\\.")
                message(FATAL_ERROR "Integration source exposes a private include: ${_file}")
            endif()
        endforeach()

        file(GLOB_RECURSE _boundary CONFIGURE_DEPENDS
            "${PROJECT_SOURCE_DIR}/EngineFramework/RuntimeBoundary/*/include/*.h"
            "${PROJECT_SOURCE_DIR}/EngineFramework/RuntimeBoundary/*/src/*.h"
            "${PROJECT_SOURCE_DIR}/EngineFramework/RuntimeBoundary/*/src/*.cpp")
        foreach(_file IN LISTS _boundary)
            file(READ "${_file}" _content)
            _epidemic_extract_includes("${_content}" _includes)
            foreach(_include IN LISTS _includes)
                if(NOT "${_include}" MATCHES "^Epidemic/Runtime/")
                    continue()
                endif()
                _epidemic_include_has_allowed_prefix(
                    "${_include}"
                    EPIDEMIC_ARCH_RUNTIME_BOUNDARY_ALLOWED_RUNTIME_INCLUDE_PREFIXES
                    _allowed_runtime_boundary_include)
                if(NOT _allowed_runtime_boundary_include)
                    message(FATAL_ERROR "RuntimeBoundary source has unapproved Runtime include ${_include}: ${_file}")
                endif()
            endforeach()
        endforeach()
    endif()
endfunction()

function(epidemic_add_public_header_self_containment_target)
    set(_generated_dir "${CMAKE_BINARY_DIR}/architecture_headers")
    file(MAKE_DIRECTORY "${_generated_dir}")
    add_custom_target(EpidemicPublicHeaderSelfContainment)
    set_target_properties(EpidemicPublicHeaderSelfContainment PROPERTIES FOLDER "Architecture")

    _epidemic_collect_targets("${PROJECT_SOURCE_DIR}" _targets)
    foreach(_target IN LISTS _targets)
        get_target_property(_type "${_target}" TYPE)
        get_target_property(_source_dir "${_target}" SOURCE_DIR)
        file(RELATIVE_PATH _relative_source "${PROJECT_SOURCE_DIR}" "${_source_dir}")
        if(NOT _type MATCHES "^(STATIC|SHARED|MODULE|INTERFACE|OBJECT)_LIBRARY$" OR
           NOT _relative_source MATCHES "^(EngineBase|EngineRuntime|EngineFramework)/" OR
           _relative_source MATCHES "/(Tests|tests|Apps|DevelopmentInfrastructure)(/|$)")
            continue()
        endif()
        file(GLOB_RECURSE _headers CONFIGURE_DEPENDS
            "${_source_dir}/include/*.h" "${_source_dir}/include/*.hpp")
        if(NOT _headers)
            continue()
        endif()
        set(_units)
        foreach(_header IN LISTS _headers)
            file(READ "${_header}" _prefix LIMIT 512)
            if(NOT _prefix MATCHES "#pragma once")
                message(FATAL_ERROR "Public header does not start with #pragma once: ${_header}")
            endif()
            file(TO_CMAKE_PATH "${_header}" _normalized)
            string(FIND "${_normalized}" "/include/" _marker)
            math(EXPR _include_start "${_marker} + 9")
            string(SUBSTRING "${_normalized}" ${_include_start} -1 _include_name)
            string(MD5 _header_hash "${_target}:${_normalized}")
            set(_unit "${_generated_dir}/header_${_header_hash}.cpp")
            file(CONFIGURE OUTPUT "${_unit}" CONTENT "#include <${_include_name}>\n" @ONLY NEWLINE_STYLE LF)
            list(APPEND _units "${_unit}")
        endforeach()
        string(MD5 _target_hash "${_target}")
        set(_consumer "EpidemicHeaderConsumer_${_target_hash}")
        add_library("${_consumer}" OBJECT ${_units})
        target_link_libraries("${_consumer}" PRIVATE "${_target}")
        epidemic_configure_target("${_consumer}")
        set_target_properties("${_consumer}" PROPERTIES FOLDER "Architecture/HeaderConsumers")
        add_dependencies(EpidemicPublicHeaderSelfContainment "${_consumer}")
    endforeach()
endfunction()

function(_epidemic_scan_generated_target_sources target relative_source)
    get_target_property(_sources "${target}" SOURCES)
    get_target_property(_source_dir "${target}" SOURCE_DIR)
    foreach(_source IN LISTS _sources)
        if("${_source}" MATCHES "^\$<")
            continue()
        endif()
        if(IS_ABSOLUTE "${_source}")
            set(_absolute "${_source}")
        else()
            set(_absolute "${_source_dir}/${_source}")
        endif()
        file(TO_CMAKE_PATH "${_absolute}" _absolute)
        file(TO_CMAKE_PATH "${CMAKE_BINARY_DIR}" _binary_root)
        string(FIND "${_absolute}" "${_binary_root}/" _generated_prefix)
        if(NOT _generated_prefix EQUAL 0 OR NOT EXISTS "${_absolute}")
            continue()
        endif()
        get_filename_component(_extension "${_absolute}" LAST_EXT)
        if(NOT _extension IN_LIST EPIDEMIC_PRODUCTION_CXX_EXTENSIONS)
            message(FATAL_ERROR "Generated production source extension '${_extension}' requires registry review: ${_absolute}")
        endif()
        file(READ "${_absolute}" _content)
        if(relative_source MATCHES "^EngineBase/" AND _content MATCHES "Epidemic/(Runtime|GameFramework)/")
            message(FATAL_ERROR "Generated EngineBase source references an upper layer: ${_absolute}")
        elseif(relative_source MATCHES "^EngineRuntime/" AND _content MATCHES "Epidemic/GameFramework/")
            message(FATAL_ERROR "Generated EngineRuntime source references Framework: ${_absolute}")
        endif()
    endforeach()
endfunction()
