include_guard(GLOBAL)

function(_epidemic_collect_targets directory out_var)
    get_property(_targets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
    get_property(_children DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
    foreach(_child IN LISTS _children)
        _epidemic_collect_targets("${_child}" _child_targets)
        list(APPEND _targets ${_child_targets})
    endforeach()
    set(${out_var} "${_targets}" PARENT_SCOPE)
endfunction()

function(_epidemic_target_rejects target pattern rule)
    get_target_property(_direct "${target}" LINK_LIBRARIES)
    get_target_property(_public "${target}" INTERFACE_LINK_LIBRARIES)
    foreach(_dependency IN LISTS _direct _public)
        if("${_dependency}" MATCHES "${pattern}")
            message(FATAL_ERROR "${target} violates ${rule}: ${_dependency}")
        endif()
    endforeach()
endfunction()

function(_epidemic_scan root pattern rule)
    if(NOT EXISTS "${root}")
        return()
    endif()
    file(GLOB_RECURSE _files CONFIGURE_DEPENDS
        "${root}/include/*.h" "${root}/include/*.hpp"
        "${root}/src/*.h" "${root}/src/*.hpp" "${root}/src/*.cpp")
    foreach(_file IN LISTS _files)
        file(READ "${_file}" _content)
        if(_content MATCHES "${pattern}")
            message(FATAL_ERROR "${rule}: ${_file}")
        endif()
        if(_content MATCHES "#[ \t]*include[^\r\n]*\\.\\.")
            message(FATAL_ERROR "Production source uses a private relative include: ${_file}")
        endif()
    endforeach()
endfunction()

function(epidemic_validate_architecture_freeze)
    _epidemic_collect_targets("${PROJECT_SOURCE_DIR}" _targets)
    foreach(_target IN LISTS _targets)
        get_target_property(_type "${_target}" TYPE)
        if(NOT _type MATCHES "^(STATIC|SHARED|MODULE|INTERFACE|OBJECT)_LIBRARY$")
            continue()
        endif()
        get_target_property(_source "${_target}" SOURCE_DIR)
        file(RELATIVE_PATH _relative "${PROJECT_SOURCE_DIR}" "${_source}")

        if(_relative MATCHES "^EngineBase/" AND NOT _relative MATCHES "^EngineBase/(Tests|Apps)/")
            _epidemic_target_rejects("${_target}" "Epidemic(Runtime|GameFramework|Gameplay)"
                "EngineBase must not depend on Runtime or Framework")
        elseif(_relative MATCHES "^EngineRuntime/" AND NOT _relative MATCHES "^EngineRuntime/(Tests|.*/tests)/")
            _epidemic_target_rejects("${_target}" "Epidemic(GameFramework|Gameplay)"
                "EngineRuntime must not depend on Framework")
            if(NOT _relative MATCHES "^EngineRuntime/(RuntimeFoundation|Support)(/|$)")
                get_target_property(_direct "${_target}" LINK_LIBRARIES)
                get_target_property(_public "${_target}" INTERFACE_LINK_LIBRARIES)
                foreach(_dependency IN LISTS _direct _public)
                    if("${_dependency}" MATCHES "EpidemicRuntime" AND
                       NOT "${_dependency}" MATCHES "EpidemicRuntimeFoundation")
                        message(FATAL_ERROR "${_target} directly links Runtime major ${_dependency}")
                    endif()
                endforeach()
            endif()
        elseif(_relative MATCHES "^EngineFramework/(BaseInfrastructure|GameplayWorldStateOwners)/")
            _epidemic_target_rejects("${_target}" "EpidemicRuntime"
                "Framework core must use an approved Runtime boundary")
        elseif(_relative MATCHES "^EngineFramework/IntegrationLayer/")
            get_target_property(_direct "${_target}" LINK_LIBRARIES)
            get_target_property(_public "${_target}" INTERFACE_LINK_LIBRARIES)
            foreach(_dependency IN LISTS _direct _public)
                if("${_dependency}" MATCHES "EpidemicRuntime" AND
                   NOT ("${_target}" STREQUAL "EpidemicGameFrameworkCoreIntegration" AND
                        "${_dependency}" MATCHES "EpidemicRuntimeTime"))
                    message(FATAL_ERROR "${_target} has unapproved Runtime dependency ${_dependency}")
                endif()
            endforeach()
        elseif(_relative MATCHES "^EngineFramework/RuntimeBoundary/")
            get_target_property(_direct "${_target}" LINK_LIBRARIES)
            get_target_property(_public "${_target}" INTERFACE_LINK_LIBRARIES)
            foreach(_dependency IN LISTS _direct _public)
                if("${_dependency}" MATCHES "EpidemicRuntime" AND
                   NOT "${_dependency}" MATCHES "EpidemicRuntime(World|Physics|Environment|Navigation)")
                    message(FATAL_ERROR "${_target} has unapproved boundary dependency ${_dependency}")
                endif()
            endforeach()
        endif()
    endforeach()

    _epidemic_scan("${PROJECT_SOURCE_DIR}/EngineBase" "Epidemic/(Runtime|GameFramework)/"
        "EngineBase source references an upper layer")
    _epidemic_scan("${PROJECT_SOURCE_DIR}/EngineRuntime" "Epidemic/GameFramework/"
        "EngineRuntime source references Framework")
    _epidemic_scan("${PROJECT_SOURCE_DIR}/EngineFramework/BaseInfrastructure"
        "Epidemic/(Runtime|Platform|RHI|RHI_D3D11)/" "Framework infrastructure bypasses a boundary")
    _epidemic_scan("${PROJECT_SOURCE_DIR}/EngineFramework/GameplayWorldStateOwners"
        "Epidemic/(Runtime|Platform|RHI|RHI_D3D11)/" "Framework owner bypasses a boundary")

    if(EPIDEMIC_BUILD_FRAMEWORK)
        file(GLOB_RECURSE _integration CONFIGURE_DEPENDS
            "${PROJECT_SOURCE_DIR}/EngineFramework/IntegrationLayer/*/include/*.h"
            "${PROJECT_SOURCE_DIR}/EngineFramework/IntegrationLayer/*/src/*.h"
            "${PROJECT_SOURCE_DIR}/EngineFramework/IntegrationLayer/*/src/*.cpp")
        foreach(_file IN LISTS _integration)
            file(READ "${_file}" _content)
            if(_content MATCHES "Epidemic/Runtime/")
                file(TO_CMAKE_PATH "${_file}" _normalized)
                if(NOT _normalized STREQUAL
                   "${PROJECT_SOURCE_DIR}/EngineFramework/IntegrationLayer/Integration/include/Epidemic/GameFramework/Integration/core_adapters.h"
                   OR NOT _content MATCHES "Epidemic/Runtime/Time/time_runtime.h")
                    message(FATAL_ERROR "Integration source has unapproved Runtime include: ${_file}")
                endif()
            endif()
            if(_content MATCHES "/src/" OR _content MATCHES "#[ \t]*include[^\r\n]*\\.\\.")
                message(FATAL_ERROR "Integration source exposes a private include: ${_file}")
            endif()
        endforeach()

        file(GLOB_RECURSE _boundary CONFIGURE_DEPENDS
            "${PROJECT_SOURCE_DIR}/EngineFramework/RuntimeBoundary/*/include/*.h"
            "${PROJECT_SOURCE_DIR}/EngineFramework/RuntimeBoundary/*/src/*.h"
            "${PROJECT_SOURCE_DIR}/EngineFramework/RuntimeBoundary/*/src/*.cpp")
        foreach(_file IN LISTS _boundary)
            file(READ "${_file}" _content)
            string(REGEX REPLACE
                "Epidemic/Runtime/(World|Physics|Environment|Navigation)/[A-Za-z0-9_./-]+"
                "" _remainder "${_content}")
            if(_remainder MATCHES "Epidemic/Runtime/")
                message(FATAL_ERROR "RuntimeBoundary source has unapproved Runtime include: ${_file}")
            endif()
        endforeach()
    endif()
endfunction()

function(epidemic_add_public_header_self_containment_target)
    set(_roots "${PROJECT_SOURCE_DIR}/EngineBase")
    if(EPIDEMIC_BUILD_RUNTIME)
        list(APPEND _roots "${PROJECT_SOURCE_DIR}/EngineRuntime")
    endif()
    if(EPIDEMIC_BUILD_FRAMEWORK)
        list(APPEND _roots "${PROJECT_SOURCE_DIR}/EngineFramework")
    endif()

    foreach(_root IN LISTS _roots)
        file(GLOB_RECURSE _found CONFIGURE_DEPENDS "${_root}/*/include/*.h" "${_root}/*/include/*.hpp")
        list(APPEND _headers ${_found})
    endforeach()
    list(REMOVE_DUPLICATES _headers)
    set(_generated_dir "${CMAKE_BINARY_DIR}/architecture_headers")
    file(MAKE_DIRECTORY "${_generated_dir}")
    foreach(_header IN LISTS _headers)
        file(READ "${_header}" _prefix LIMIT 512)
        if(NOT _prefix MATCHES "#pragma once")
            message(FATAL_ERROR "Public header does not start with #pragma once: ${_header}")
        endif()
        file(TO_CMAKE_PATH "${_header}" _normalized)
        string(FIND "${_normalized}" "/include/" _marker)
        math(EXPR _end "${_marker} + 8")
        string(SUBSTRING "${_normalized}" 0 ${_end} _include_root)
        list(APPEND _include_roots "${_include_root}")
        string(MD5 _hash "${_normalized}")
        set(_unit "${_generated_dir}/header_${_hash}.cpp")
        file(WRITE "${_unit}" "#include \"${_normalized}\"\n")
        list(APPEND _units "${_unit}")
    endforeach()
    list(REMOVE_DUPLICATES _include_roots)
    if(_units)
        add_library(EpidemicPublicHeaderSelfContainment OBJECT ${_units})
        target_include_directories(EpidemicPublicHeaderSelfContainment PRIVATE ${_include_roots})
        epidemic_configure_target(EpidemicPublicHeaderSelfContainment)
        set_target_properties(EpidemicPublicHeaderSelfContainment PROPERTIES FOLDER "Architecture")
    endif()
endfunction()