add_library(EpidemicGameFrameworkInteractionEffectsIntegration STATIC src/interaction_effects_adapter.cpp)
target_include_directories(EpidemicGameFrameworkInteractionEffectsIntegration PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/include")
target_link_libraries(EpidemicGameFrameworkInteractionEffectsIntegration PUBLIC EpidemicGameFrameworkInteraction EpidemicGameFrameworkEffects PRIVATE EpidemicFoundation)
epidemic_configure_target(EpidemicGameFrameworkInteractionEffectsIntegration)
